### ISSUE TITLE
Running gulp on cloned repo give error "jekyll-sitemap"

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#101]
```
Configuration file: C:/Git/ucsb-wsg.github.io/_config.yml

jekyll 3.1.1 | Error:  jekyll-sitemap
```

![image](https://cloud.githubusercontent.com/assets/4443025/12956975/7735797a-cfdf-11e5-88da-11a2c08c0a30.png)

**Comment by loganfranken** [comment]
I think this might be because `jekyll-sitemap` isn't in the Gemfile (https://github.com/ucsb-wsg/ucsb-wsg.github.io/blob/master/Gemfile)?

**Comment by garster** [comment]
@loganfranken yes and no. I added but still error. I discovered I needed to install "bundler" and run the "bundle" command. It finally installed it and I no longer get the error, but then running gulp does not stand up a server at localhost:4000, which I will open in a new issue.

**Comment by loganfranken** [comment]
Ahh, nice, looks like you added Bundler to the list of required tools in that PR too.

**Comment by loganfranken** [comment]
Merging #108 should address this one, right?
