### ISSUE TITLE
Running Gulp does not stand up webserver on port 4000

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#109]
Per the Developer Readme, the instructions say after yo run the `gulp` command you can visit http://localhost:4000/ to view the site.

This did not work in my case.

**Comment by loganfranken** [comment]
Did you happen to get any exceptions or anything? This _should_ work, although in my experience it does take a little bit (we should probably find a way to put more helpful messaging out there)

**Comment by garster** [comment]
When I run Bundle I get a ton of errors. Maybe Bundle is not the right command, but what I goggled it is the way to get things from Gemfile installed.

![image](https://cloud.githubusercontent.com/assets/4443025/14156086/76b07dea-f679-11e5-8cc1-43b07304012e.png)

![image](https://cloud.githubusercontent.com/assets/4443025/14156099/85a01298-f679-11e5-99ca-60a9d08ab0c0.png)

**Comment by tenken** [comment]
@garster when building Gems for a system you typically need the development header files for Ruby and the underlying build essentials for your linux distributions (make, autoconf, build, etc). On ubuntu this would be something like `ruby-dev` and `build-essentials` packages.
