### ISSUE TITLE
Valid and complete Development Instructions needed.

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#112]
To reduce the barriers of entry on working on the webguide the developer readme needs to have instructions on the steps needed to build from the ground up with no prior tools installed. 

We need to give everyone, including ones not familiar with the GitHub tools, the chance to work on the site.

In my personal experience I have installed various tools and tried to discover what is needed to run and test the site locally and have yet been able to do that after wasting hours on the process.

**Comment by tenken** [comment]
I've given a fair amount of thought to this off and on. I think comprehensive documentation on this will be cumbersome and hard to maintain. 

I recommend an alternative. Supply a pre-configured system for people to edit on and some documentation on how best to use that tool. For example a Vagrant virtualbox image you can interact with as a developer with all the dependencies setup. Then Co-Chairs could (try) to keep the vagrant box/images up-to-date for aspiring developers:
http://superuser.com/questions/584100/why-should-i-use-vagrant-instead-of-just-virtualbox

Various example vagrant file configurations exist (I have not tested these, but they could offer a good starting point to Fork from):
http://lmgtfy.com/?q=vagrant+github+pages

I'll see if I can think of or research other solutions.

**Comment by garster** [comment]
Yep I installed ruby dev tools and got father but jekyll-sitemap was still broken, even after adding it to the Gemfile as suggested earlier. It seems to me that the few people that work on this have the correct toolset installed so it just "works" for them. 

My problem is not to create "comprehensive" docs like go to XYZ, click next, etc, but to just list out the tools and steps to go from zero to built. Right now the development readme is fiction and the build chain is obviously broken since it only runs on systems that are already setup

I am willing to do this, but I know zip about ruby, gems, gulp etc and it will take time to reverse engineer the process as opposed to someone who knows the tools and can validate the build chain.

**Comment by tenken** [comment]
I hear where you're coming from. Unfortunately some of the development practices for Ruby vary from OS to OS, since ruby isn't a 1st class citizen of any OS.

A simple set of notes for Ubuntu wouldnt apply for example on OSX -- which has no native package manager. So there's always a certain level of (pre-existing knowledge) needed to setup the toolchain anywhere, with intimate knowledge of the underlying OS. That's why I suggested getting rid of that barrier by opting for an alternate developer solution involving a pre-configured image.

Then if people seek to contribute -- contributors using the image, and the maintainers of the image speak 1 language. The language of the image and not: Well on Windows you need X,Y,Z but on OSX or linux you need 1 of N other libraries ... etc.

If requested I can help write up a Ubuntu LTS contribution guide.

**Comment by garster** [comment]
I got it to work after much google-fu and swearing, and not by following the Developer Readme. I will loo kin Vagrant and submit a PR for an updated Developer Readme that included the terms "Good luck with that".

**Comment by loganfranken** [comment]
I think there's got to be a middle ground we can strike here somewhere: I totally agree that we can't maintain a finely detailed set of instructions, but we might be able to provide a little more context for each step of the installation process, at least providing links to instructions on how to install for the various environments.

I'm not sure of the best path forward: maybe someone can try setting up the project on a fresh machine and documenting the steps they took? Or we could ask someone to try setting it up for themselves and ask them to report any pain points here (which we can make sure have corresponding documentation in the developer README)?

**Comment by loganfranken** [comment]
Could we bring this up again at the next WSG meeting? We need someone to volunteer to try this out.

**Comment by garster** [comment]
I found one of my issues is Jekyll is not "officially" supported on Windows.

**Comment by garster** [comment]
I was able to get this to work on Windows. I will take on this task.

**Comment by garster** [comment]
So now the build stack is getting crazy! For some reason npm install wanted to compile node-sass with Visual Studio which fails.  I think it is time to look at the stack and simplify, maybe move to Webpack for sass and minification.

![image](https://user-images.githubusercontent.com/4443025/31361643-13c57c42-ad09-11e7-8986-08256a694194.png)

**Comment by garster** [comment]
I'm finally working on this. I found updating the packages helped on windows. I will submit that via a separate issue.

**Comment by garster** [comment]
I'm back on this!
