### ISSUE TITLE
dead link on footer page

### ISSUE THREAD

**Issue by ilessing** [UCSantaBarbara/webguide#116]
dead link found on this page: http://webguide.ucsb.edu/footer/

link text: UCOP Copyright Matters.
bad URL:  http://www.ucop.edu/ott/faculty/crprimr.html  (404) error

**Comment by garster** [comment]
Anyone know a good replacement page?

Maybe http://www.ucop.edu/terms/
or this: http://copyright.universityofcalifornia.edu/

**Comment by loganfranken** [comment]
Yeah, I think http://copyright.universityofcalifornia.edu/ is the way to go: anyone have issues with that?
