### ISSUE TITLE
Consider serving the webguide from Gitlab to support SSL

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#120]
Gitlab is a competing service to Github. Recently they rolled out GitlabPages which are a "clone" of the Github Pages feature found on Github.

Additionally GitlabPages supports SSL for both gitlab hosted sites, and those running under a custom domain.

Gitlab Pages supports SSL by providing a location for you to upload a cert to their server from your account -- something Github has yet to implement in a very long time, with no foreseeable ETA.

An example of setting this up is at:
https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/

Here are the items of a Github repository that can be imported to Gitlab:
http://doc.gitlab.com/ce/workflow/importing/import_projects_from_github.html

Note the exceptions:

> It is not yet possible to import your labels, milestones and cross-repository pull requests (those from forks). We are working on improving this in the near future.

Gitlab supports the concepts of Groups, but I don't know if they:
- support the idea of faux Organizations like Github does.
- In the recent past their uptime has been suspect. (but then, so has Github).

If anyone wants to attempt making a faux ucsb-webguide.gitlab.com for example using SSL as a testcase there's no reason the 2 services couldnt be running in tandem for testing purposes.

Feedback is appreciated (I wonder if Github could stay as-is) and a Push to a gitlab instance just host the display of the site under SSL ...

**EDIT**
- The manual SSL management currently on the gitlab accounts will be automated in the future: https://gitlab.com/gitlab-org/gitlab-ee/issues/474  I assume Github is working on something like this for an ... eventual release.

**Comment by tenken** [comment]
Related to #117

**Comment by garster** [comment]
I bet GitHub will bring this feature out soon. Plus I already solved the problem by reverting my lame idea to embeding the calendar in the first place.

**Comment by loganfranken** [comment]
GitHub Pages now support HTTPS...
https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

...but, unfortunately, not over a custom domain. We're getting closer, though!

**Comment by loganfranken** [comment]
Are we leaving this ticket open until we have SSL support? Or do we need to mark this (a move to Gitlab) for discussion in the next WSG meeting?

**Comment by loganfranken** [comment]
Based on the group discussion today, it sounds like we'll stick with GitHub unless someone wants to research (and present on) exploring a possible migration to GitLab or other similar platform.

With that, I would recommend we close this issue unless someone wants to pick it up.

**Comment by loganfranken** [comment]
How does everyone feel about closing this issue (unless someone wants to take it over)?

**Comment by tenken** [comment]
Since I opened this issue, I'll go ahead and close it now :) Thanks Logan.
