### ISSUE TITLE
Add Note About Preferring HTML over PDFs

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#130]
From the accessibility guide:
https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#11-use-w3c-technologies-and-guidelines

> Use accessible technology specified by W3C such as HTML and CSS while avoiding PDF and Shockwave which is not as readily accessible. When utilizing PDF documents provide an alternative HTML page wherever possible. Alternatively, PDF documents may be used PROVIDED they meet the accessible PDF guidelines listed below.

**Comment by garster** [comment]
:clap:
