### ISSUE TITLE
Add WebAIM Link

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#134]
From the accessibility guide:
https://github.com/ucsb-wsg/web-accessibility/blob/master/web-accessibility-guidelines.md#resources

The W3C link is already on the Web Accessibility page:
http://webguide.ucsb.edu/web-accessibility/

Just need to add the WebAIM link as well.

**Comment by garster** [comment]
@loganfranken Should this be closed since WebAIM is no longer an UCSB option?

**Comment by loganfranken** [comment]
Hey @garster, were you thinking of the AMP accessibility scanning tool? WebAIM should still be a viable general resource.

**Comment by garster** [comment]
@loganfranken yes I think you are correct and I am mistaken.
