### ISSUE TITLE
Make Use of Sass Functionality

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#141]
Per suggestions in #140, the Sass file should be upgraded to actually make use of Sass's functionality.

**Comment by ericmayes** [comment]
I do have a SASS version of this CSS that I'm using for the new GOLD layout that has most of the same pieces, however it more closely matches UCSB home at the moment. In this version, SASS variables are set for colors, viewports, and then some mixins for prefixes. It looks like public affairs used Compass to get most of the prefixes for things like boxshadow, rotate and transform (both used on the hamburger). Border radius is also used but to my knowledge not needed. There are only a few lines of code being saved in the final output from these prefixes. There could be more I didn't see but I don't think so. Also, most of the nested SASS areas are for the navigation piece. Other than that, just for breakpoints. So we should be able to use some of the existing sass pieces with a few changes. (For instance just using the larger main nav SASS and also the SASS color variables) It might be a good idea as long as it required minimal effort. 

Still not sure about the ease of use for updating the css live via github using SASS. Will Git actually recompile the CSS files for us if we made changes to the SCSS files? If that's the case that would be really cool and easy to maintain.

**Comment by tenken** [comment]
Github Pages, the underlying service within Github running the website supports SASS files natively for some time:
https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0

> Native Sass & CoffeeScript support - Simply commit a .coffee, .sass or .scss file to your site's repository, and GitHub Pages will transparently output JavaScript or CSS when your site is published.

So in short, the answer is Yes. Although the infrasture doesn't support a Preview option (outside of a local Fork of the project, as Logan recently did for his redesign preview) so 1 wrong typo and the SASS file (beyond that point in the file) or in variable usage will likely break the generated output.

Git is a single component used within the infrastructure and services github provides.

It'd be great to merge the SASS pieces you mention @ericmayes !

**Comment by loganfranken** [comment]
Hey @ericmayes, did you have that Sass version? If not, I can take a pass at upgrading it myself. Let me know; thanks!

**Comment by ericmayes** [comment]
Hey @loganfranken! Sorry for the slow reply I was out on vacation.  I have new scss files I created for GOLD that were based on some of the same CSS. What I could do is take those and then remove the SASS we wouldn't need, change a couple of variable definitions, and then export and compare to our current CSS. Once I got it to match then I could send it to you. Right now GOLD is my main priority so I'm not sure when I could get to it. Probably sometime within the next month or two? Not sure how soon the group would like the SASS version in place. What do you all think?

**Comment by loganfranken** [comment]
Hey @ericmayes! No need to be sorry! In my opinion, there's no rush at all (but I'd love to hear what everyone else thinks)

**Comment by garster** [comment]
I think this would be a nice undertaking. The main.scss file has an http import to google fonts (change to https) and no variables.

I would do the work of turning some of the repeated properties into variables, but someone else will need to test since I can;t build the site.

**Comment by ericmayes** [comment]
@garster I'm hoping to revisit the SASS conversion soon. A few other projects have come up. I have a good bulk of the SASS pieces already. just need to tidy up some things. Probably a couple days of work whenever I can get to it. If we need to move on it quicker I can try to figure something out.

**Comment by garster** [comment]
@ericmayes good, cause I know very little about sass. Its all your's

**Comment by loganfranken** [comment]
Hey @ericmayes! Do you have any of those pieces lying around you mentioned? If so, I could tidy them up. Just let me know; thanks!

**Comment by ericmayes** [comment]
I do! Thanks for the reminder! I think there was just some extra stuff to be ripped out, but its mostly there besides any new changes since the 1st version. I can package what I have today and put up a public link on Box :)

**Comment by ericmayes** [comment]
https://ucsb.box.com/s/2uh3ljg377uddzg2dcmhby3k80rr2kve

@loganfranken So this version is good, but there are a few parts that weren't SASS-i-fied completely. I redid those parts in a new version of our standard template. So when you see any of those pieces (they stand out since they aren't nested), you could copy those sections from our repository here: 
$/Ucsb.Sa.Ssis/Ucsb.Sa.Ssis.Ssis/Ucsb.Sa.Ssis.Ssis.Sitefinity.StandardTemplate/MVC Resources/ResourcePackages/UcsbStandardPackage/assets/dist/css
I would say just use that version but there are quite a few more changes from the original version, but you can go ahead and check it out.

Also in the zip I sent you, right now the main Layout.scss wont compile until you remove the two missing scss : legacy and tabstrips which you wont need for WSG. LMK if there are any questions along the way!

**Comment by loganfranken** [comment]
Thanks @ericmayes!

Taking a closer look at this, it looks like @tenken's original suggestion (in #140) was to use variables to clean up colors. I'm no longer a huge fan of the Sass features beyond variables (e.g. nesting, mixins, etc.), so I just went ahead and swapped out the magic hex codes for Sass variables.

Unless anyone disagrees, I think this should resolve the ticket.
