### ISSUE TITLE
Consider Making Google Font Local

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#143]
Per suggestion in #140, consider making Google Font a local resource.

**Comment by garster** [comment]
I would rather use the CDN for the font, but I would change it to the https url.

What is the thoughts around bring it "local"?

**Comment by tenken** [comment]
If you look at the changes from the merge commit; in the previous site templates most of the site JS assets were served from a CDN. For whatever reason now 3 are served locally via minified files and the font is included via CDN. As a developer I'd simply want as much consistency as possible in how asset files are included on the site.

Also, the main benefit of all files being locally hosted is to assure we're not dependant on a CDN being up for the site to look ok. The CDN is a failure point.

Lastly moving the font to a local file is not a ton of work. Mainly copying the directives found in the CDN file now and creating a local file and assuring it's included prior to styles that need it.

The only downside is if the font is actively updated by Google we'd miss out on automated updates to the font. Meh.

**Comment by garster** [comment]
Ok @tenken I like the "consistency" argument. And I agree on Meh for the updates. Its a font, it should not need updating.
