### ISSUE TITLE
Add Padding to Main Content Area

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#147]
Per @ericmayes's suggestion in #140:

> We also might want to add a little more padding to the main content area, with the actual content added instead of my test content it almost looks like the content expands past the menu and footer boxes (even though it doesn't)

**Comment by garster** [comment]
@ericmayes can you provide some screenshots of what you mean?

**Comment by ericmayes** [comment]
There are a few classes that override some Bootstrap defaults. Its a bit harder to notice unless the browser around 1025px, but the content is wider than our navigation section. We could just adjust those negative margins in the main.css file to be positive. I also attached a screen showing the issue. 

`.row {
    margin-right: -10px;
    margin-left: -10px
}`

should be 

`.row {
    margin-right: 10px;
    margin-left: 10px
}`

![image](https://cloud.githubusercontent.com/assets/7233610/19866819/d4f440ce-9f5e-11e6-9266-aa7c2977e968.png)

**Comment by loganfranken** [comment]
Hey there! I tried to recreate this one and can't: @ericmayes, are you still able to recreate this one? Or did it somehow get fixed? Can anyone else recreate this one?

**Comment by ericmayes** [comment]
I'm able to edit the class .row in the dom inspector to reflect this change. Our row class overrides the bootstrap row class. Might not be the best approach to override that but I think its the only instance of row on the site besides the container for the UCSB wordmark logo which this change doesn't seem to affect.

![image](https://cloud.githubusercontent.com/assets/7233610/21616349/f010875a-d195-11e6-96fc-7c3876a1b6c8.png)

**Comment by garster** [comment]
I think the fix @ericmayes demonstrates looks good. I don't see the need for the negative margins. 

![image](https://cloud.githubusercontent.com/assets/4443025/21616965/afc8edce-d198-11e6-9807-fc28750c7c52.png)

**Comment by loganfranken** [comment]
Sorry, to be clear: I'm down for this change; it totally makes sense to me.

However, I can't personally recreate the before state (the content being wider than the navigation) to verify that the fix has the intended purpose (it looks aligned to me in all viewports, tested in both Chrome and Firefox).

Since I can't verify it myself, I'll leave this one open for someone else to take a crack at it.

**Comment by ericmayes** [comment]
This really is just a nit picky thing and you are totally right @loganfranken the content is right on the edge of the width defined by the nav. In the large viewport, the container with class row is rendering at 1220px wide when the nav is 1200 but the padding supplied in the content area keeps the content in line with the nav bar. Its probably fine the way it is, but we could either change the margins to positive 10 or even just make them 0 (which actually makes the container 1200). This change was really just my opinion on what looked better when I worked on the new look. But going back to the UCSB homepage the content does indeed go to the very edge (although a left sidebar is always present and you don't notice it as much - its really the left edge that bugs me lol) We are probably fine without the change! Its really more of an optical illusion than anything. 

![image](https://cloud.githubusercontent.com/assets/7233610/21693428/c18563a0-d335-11e6-9020-e39403c3cd9f.png)

**Comment by loganfranken** [comment]
Hey @ericmayes! No need to doubt yourself! (You're the designer, after all!)

I was more speaking from a technical perspective (I wanted to be able to see the problem we were fixing before fixing it), not critiquing the fix itself.

Now I think I'm on the same page: so the idea is that the content _is_ flush with the navigation, it just _looks_ like it isn't flush because the width of the container is larger, right?

If so, I can take another crack at this.

**Comment by ericmayes** [comment]
Thanks @loganfranken! So yes, the content is flush but it could come in just a tad IMO. If the container goes to 1200 or 1180 (by reducing that negative margin) then the content will come in as well.
