### ISSUE TITLE
Level 4 Headings Are Smaller Than Body Text

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#169]
See:
http://webguide.ucsb.edu/

**Comment by garster** [comment]
I could not see what you were describing on that page. Do you mean h4 tags? By default header tags can be smaller then body text.

See: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_headers

**Comment by loganfranken** [comment]
Yeah, exactly: I meant the H4 tags. I feel like headers _shouldn't_ be smaller than the body text since they no longer visually present as headers, but I'm totally open if the group feels otherwise.
