### ISSUE TITLE
Include Content From "UC’s Important Security Controls for Everyone and All Devices"

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#173]
Today, we discussed including content from the new "UC’s Important Security Controls for Everyone and All Devices":
http://security.ucop.edu/guides/security-controls-everyone-all-devices.html

**Comment by loganfranken** [comment]
Revisiting this: these tips look specific to personal devices?

I don't necessarily think it makes sense to include these tips in the Web Guide, but I'm totally open.

**Comment by garster** [comment]
@loganfranken I agree. These are more related to http://www.security.ucsb.edu/ and outside the scope of Web Standards. I am closing the issue.
