### ISSUE TITLE
Consider updating the copyright information on the footer page

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#192]
Putting a copyright notice on a webpage is optional from a legal standpoint.

Putting the year can be troublesome. There are differing opinions on when to update teh year. Should it be updated on major revisions, on any change, keep it the current year, or just remove the year entirely.

I had a discussion with Katie Fortney, the UCOP Copyright Policy and Education Officer about this. I do not want to share her email in this public GitHub issue, but I will bring it up in a WSG meeting.

I suggest we update the information about the copyright footer to allow for more flexibility.

**Comment by philipjfried** [comment]
With OceanO, my go-to is:
<p>&copy; <?php echo date("Y") ?> The Regents of the University of California</p>
...or some clients like to show off long they've been around, so you make them happy with:
<p>&copy; 1999-<?php echo date("Y") ?> The Regents of the University of California</p>

**Comment by rvizena** [comment]
For OceanO, my go-to is:
`<p>&copy; <?php echo date("Y") ?> The Regents of the University of California</p>`

**Comment by dsaludares** [comment]
The University of California’s Copyright site recommends a format for copyright notice in one of their FAQs:

http://copyright.universityofcalifornia.edu/faqs/index.html#h

It includes the “Copyright” word or symbol “followed by the year of first publication and then the name of the copyright owner.”

**Comment by loganfranken** [comment]
I can't remember: where did we land on this? How did we want to update our recommendations?

**Comment by garster** [comment]
I have it on my plate, I just need to do it... like now.
