### ISSUE TITLE
Remove Web Accessibility Guide PDF

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#195]
After #164 is complete, this will complete all of the remaining work items for ensuring that the existing Accessibility PDF guide content is represented somewhere in the Web Guide (see: https://github.com/ucsb-wsg/web-accessibility/issues/9).

With that, the PDF can be completely removed.

**Comment by garster** [comment]
#164 is merged! Awesome work, thank you for your support.
