### ISSUE TITLE
Broken links on Footer page related to policy terms of use

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#198]

**Comment by dsaludares** [comment]
There are 2 more broken links on the Footer page, one under "Terms of Use" and the other under "Privacy Notification."  Both sections have a bullet that says, "Include the content of the source document on your website via a server-side technology (PHP, ASP.NET, etc.)."  The links to "source document" for each bullet are broken, but I do not know what they need to point to.

**Comment by loganfranken** [comment]
Ahh, nice catch! Thanks! Updated the PR to cover that second broken link

**Comment by dsaludares** [comment]
Oops!  I should have checked the first commit to see that you already corrected the first broken link.  Still a newbie to Git and GitHub.  Sorry!

**Comment by dsaludares** [comment]
Sorry to bother again, but http://www.policy.ucsb.edu/terms_of_use/ actually redirects to http://www.policy.ucsb.edu/terms-of-use  (The underscores changed to hyphens.)

Can "terms_of_use" be changed to "terms-of-use" wherever it appears on the Footer page, or should this be a new issue?

**Comment by loganfranken** [comment]
No need to be sorry! A thorough code review is no bother at all!

I updated the PR w/ all references to "terms_of_use" changed to "terms-of-use"

**Comment by loganfranken** [comment]
In the meeting today, we decided that the current "two bullet" message is redundant: instead, we should just say, "Link directly to the resource OR embed the content using a server-side technology"

**Comment by loganfranken** [comment]
Alright: made this update in the PR

**Comment by dsaludares** [comment]
Thanks, Logan!
