### ISSUE TITLE
Move Best Practice Examples to Separate Repo

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#2]
I think the "Best Practice Examples" should be moved into their own repo (http://www.ucsb.edu/webguide/best-practice-examples).

This would allow the examples to evolve independently from the guide itself.

**Comment by loganfranken** [comment]
URL of the page in the GitHub-hosted repo:
http://ucsb-wsg.github.io/best-practice-examples/

**Comment by loganfranken** [comment]
I can take lead on this, but I would like to propose _only_ converting the "responsive layout" version and _not_ the "fixed width" version.

I think there are definitely valid use cases for creating device-specific experiences, but I would argue this is more the exception than the majority.

A responsive design should be the default and I think we doom people into unintentionally not supporting devices by not promoting responsive as the default.

On top of all this, both the current fixed width and responsive sites (http://www.ucsb.edu/webguide/best-practice-examples) are just "versions" of each other. Basically, the "fixed width" version is just the responsive version with a class `fixed` on the `body` element. Given this, we can still provide people an easy way to opt in to the fixed width if desired.

**Comment by tenken** [comment]
A related issue (somewhat) brought up by attendees of the 05-05-2015 WSG meeting is that the whole webguide site should be updated to reflect the newest soon to be released design of the main campus homepage in about 2-3 months time.

Currently all the best-practices example share the theme of the main webguide. A discussion and formal vote should be given at the next WSG meeting (06-02-2015) to see how the group desires these themes to appear.

**Comment by tenken** [comment]
related to #21

**Comment by loganfranken** [comment]
I've created a separate repo to demonstrate how this would work:
https://github.com/loganfranken/ucsb-wsg-best-practice-examples
http://loganfranken.github.io/ucsb-wsg-best-practice-examples/

For the purposes of having a friendly URL, I think we should create the new repo at:
https://github.com/ucsb-wsg/best-practice-examples/

As noted above, having a "fixed width" layout is as easy as applying a style to the body element:
https://github.com/loganfranken/ucsb-wsg-best-practice-examples/blob/gh-pages/style/main.css#L327

I think we can move forward with this without waiting for a decision on how the Web Guide should track UCSB's look, but I'll leave up to you guys a co-chairs to decide.

**Comment by tenken** [comment]
Hi, I say we move on this. Myself or James will create the new WSG github organization project repository later today.

**Comment by tenken** [comment]
This repository has been created at:
https://github.com/ucsb-wsg/best-practice-examples

**Comment by loganfranken** [comment]
Augh, sorry: for this we'll need to also create a `gh-pages` branch off `master`.

**Comment by tenken** [comment]
done.
-dg

---

David Gurba
Instructional Development
Artworks Web Programmer
x3789
