### ISSUE TITLE
Hosting: github vs ucsb subdirectory vs ucsb subdomain

### ISSUE THREAD

**Issue by fablio-work** [UCSantaBarbara/webguide#20]
Want to get a discussion going on the pros/cons of the various hosting options available for the UCSB Webguide.  In prior years the discussion was brought up at both the WSG at large and the update subcommittee about the importance of branding and being hosted as part of the ucsb.edu web presence.  The thought was that being hosted there added to the "credibility/legitimacy" of the webguide.

With migrating the site to github and jekyll, it would be simpler to just use that git hosted version of the repo as the primary web presence.  

**Does doing that reduce the "credibility/legitimacy" of the webguide?**

Hosting the webguide under ucsb.edu would require some effort.  A workflow would need to be established to get an html copy of the site onto the ucsb.edu hosting system.  But that workflow could potentially be as simple as a recursive wget configured on the ubuntu server.

While its unlikely that we can make the github hosted version appear to operate from a subdirectory of the ucsb.edu website, we could pursue a vanity subdomain (webguide.ucsb.edu or wsg.ucsb.edu) that could be pointed at the github hosted version.  This may be an acceptable compromise.

**Is that an option worth pursuing?**

**Comment by tenken** [comment]
Regarding the vanity subdomain, I sent a request to the UCSB hostmaster for like _webguide.ucsb.edu_ as a domain for the webguide. I also asked if it was feasable technically and politcally, I sent them a link to the relevant Github directions:

https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

I have not heard back from them, but when I do I will inform the group.

**Comment by fablio-work** [comment]
Thanks David,
  I was getting ready to do that myself.

## The political may not be quite as bad, since we do not actually need the subdomain delegated to any particular group, merely a couple DNS records pointing to the right place.  But that has it's own implications, so we will see :-)

Aaron J. Martin
Computer/Network Technologist
Earth Research Institute
6809 Ellison Hall
MS-3060 UC Santa Barbara
Santa Barbara, CA 93106

805-893-8415 voice
805-893-8649 fax
http://www.eri.ucsb.edu

**Comment by loganfranken** [comment]
(Related to #14)

**Comment by loganfranken** [comment]
I vote for either (1) a vanity subdomain (if possible) or (2) a straight redirect over to GitHub.

I would strongly argue against mirroring over to the UCSB servers (I realize I'm probably preaching to the choir here): either it will be a manual process that may leave the two guides out of sync if someone's busy or it will be an automated process (as you describe @fablio-work) at which point it seems to be just an unnecessary link in the chain.

From a more philosophical perspective, hosting the Web Guide on GitHub further encourages and legitimizes the use of open-source at UCSB, which I think is important.

**Comment by UCEAP-JCOLON** [comment]
Just for the record I vote for a vanity subdomain..
Lets see if Kevin S. can work magic and support the idea..

**Comment by tenken** [comment]
This issue is resolved with #45
