### ISSUE TITLE
Formatting Under "About > Purpose" is Mushed Together

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#204]
The formatting under the headline "Purpose" (http://webguide.ucsb.edu/about/) is all mushed together. Looks like it needs to be split up into either paragraphs or lists.

**Comment by garster** [comment]
@loganfranken, ya @dsaludares and I found it too when we worked on that page, but did not log it yet. Thanks! :smile_cat: 

It was a numbered list but when we use markdown to create it, it does not work for us.
