### ISSUE TITLE
Consider Recommending @print Over Print-Specific Stylesheet

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#213]
Currently, we recommend a separate print stylesheet on the Header page:
http://webguide.ucsb.edu/header/#print-stylesheet

We should compare the pros/cons of using this approach versus using a `@print` media query.

**Comment by ericmayes** [comment]
I like the media query approach. It's just cleaner to have everything in one place (and hopefully in its own scss file too). I like how bootstrap does it with their .visible-printX and .hidden-print classes. Although these extra classes have to be added to the HTML, its so easy to add them to your template with out figuring out what rules you need to set inside the @print media query. But to the point, separate print style sheets seem  a bit outdated. I may be wrong. Maybe they are useful in some cases.

**Comment by garster** [comment]
I have not researched the difference yet but some things come to mind.

1. Both media="print" and @print work the same way. The former allows the author to place it in a separate file if they choose. @print would be used for in page css or a single external file. They both are valid and necessary depending on how the author chooses to layout the files.

2. I feel printing of webpages is rare. Also most use cases I see are a separate print view, a button that pulls up a minimal page. In 20 years I never used the print media query, but did the later with a button to load a different page.

3. If we want to talk "outdated" we should not even mention anything less then IE 11. If you are running an older browser you have big problems and need to upgrade ASAP.

**Comment by sbbeachvball** [comment]
I can see mentioning both for the time being.

**Comment by garster** [comment]
I've thought about this some more and after reviewing the CSS page. I am on board with the @print media query in the *same* stylesheet file as the rest of the CSS.

- One less file to download.
- Having the print separate could introduce bugs as the main stylesheet changes. If the @print is right there it will be noticed and kept up to date.
- Also, what happens if you compress all your CSS files into one file. How will it work without the @print media query?

@ericmayes I am seeing your "cleaner" now.

**Comment by loganfranken** [comment]
It looks like the only real downside is that `@media` query might lack some IE8 (and below) support:
https://joshuawinn.com/css-print-media-query/

Of course, this is IE8 _when_ the user is printing, so that's a pretty narrow use case IMO.

Otherwise, it makes sense to have the styling rules all together in the same place. I'll put together an update for this.

**Comment by garster** [comment]
Effective January 12, 2016, Internet Explorer 8 is no longer supported on any client or server version of Windows.
