### ISSUE TITLE
Remove Or Update Policies Timestamp

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#219]
The Policies page (http://webguide.ucsb.edu/policies/) says that "This page was last reviewed by WSG members in September 2014.", but the page was recently updated.

Should we update this timestamp?

Is this a timestamp that should only be updated when the entire page is reviewed? If so, is there a process in place to make sure that occurs on a regular basis?

Or is this something we should just remove since it's a page that continues to evolve? (This is my suggestion but I would to love hear everyone else's opinions)

**Comment by dsaludares** [comment]
Hi @loganfranken 

I agree with your suggestion to remove the timestamp.  If we do decide to keep it, we may want to consider adding a timestamp to other pages of the Webguide as well for consistency.
