### ISSUE TITLE
Update examples to HTML 5

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#22]
With HTML 5 quickly becoming the default standard, our "good examples" should be updated to reflect that direction.

Most work would be to confirm that attributes are correct and to remove any self-closing tags. `<img />` becomes `<img>` for example.

**Comment by loganfranken** [comment]
:+1:

We may need to tread carefully in regards to accessibility and the new HTML5 elements, but I'm all for this.

**Comment by garster** [comment]
@loganfranken http://ishtml5ready.com/ :smile:

**Comment by loganfranken** [comment]
@garster Hahaha :grinning: 

It looks we should be pretty good on the accessibility front too (http://www.html5accessibility.com/)

**Comment by loganfranken** [comment]
Related to this: I've also got a PR out there for fixing some HTML5 validation issues with the best practice examples: https://github.com/ucsb-wsg/templates/pull/3

**Comment by loganfranken** [comment]
Let me know if I missed anything, @garster!
