### ISSUE TITLE
Accessibility Page Broken Links

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#233]
There are a few broken links on this page:
http://webguide.ucsb.edu/web-accessibility/

* Link to non-existent PDF (UCSB Web Accessibility Guidelines (PDF))
* Section 504 Fact Sheet
* Section 255 of the Telecommunications Act of 1996 (I get a "connection reset" error)
* Section 504 of the Rehabilitation Act of 1973 Full Text
* Section 508 of The Rehabilitation Act of 1973 Full Text
* Section 255 of The Telecommunications Act of 1996 Full Text
* The Americans with Disabilities Act of 1990 Full Text
* "Section 508" link under "U.S. Department of Justice"

**Comment by dsaludares** [comment]
Fixed in #248
