### ISSUE TITLE
Markup Doesn't Validate

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#237]
Our markup doesn't validate:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwebguide.ucsb.edu%2F

**Comment by garster** [comment]
@loganfranken 

![tenor](https://user-images.githubusercontent.com/4443025/28600218-81d7b234-7165-11e7-9d55-f9d2c60fd3b2.gif)

**Comment by loganfranken** [comment]
The markup now validates! Closing this issue!
