### ISSUE TITLE
Best Practice Examples URL Conflict

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#24]
Alright, so I was a little shortsighted in my URL suggestion for the Best Practice Examples.

Now the best practice example is hosted here:
http://ucsb-wsg.github.io/best-practice-examples/

Which is awesome, but it sits on top of the existing section of the Web Guide with the same name.

On the old guide, the **section** was located here:
http://www.ucsb.edu/webguide/best-practice-examples

But the actual **template** was located here:
http://www.ucsb.edu/webguide/best-practices/template/responsive.html

So we have two options (as far as I see):
1. Rename the new Best Practice Examples repo to something else
2. Move the "Best Practice Examples" section to a different URL

As much as I hate breaking URLs, I'm leaning towards the second option.

Any opinions?

**Comment by fablio-work** [comment]
I am fine with either one.  I am not as concerned about breaking URLs, since we broke ALL of the URLs
during the last major webguide update when we followed our own advice and removed the file suffixes :-)

Granted thats two years ago now, but search engines will square all that away within a few months.

As far as renaming, what are you thinking?

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by ilessing** [comment]
I'm in favor of option 2 "move to a new URL"

**Comment by loganfranken** [comment]
For new URLs, I was just thinking:
`http://ucsb-wsg.github.io/best-practice`

Or maybe:
`http://ucsb-wsg.github.io/examples`

Or, if we wanted to be explicit, something like:
`http://ucsb-wsg.github.io/best-practice-examples-intro`

Any preferences?

**Comment by garster** [comment]
I like `http://ucsb-wsg.github.io/examples` because examples is what it is. 

"best-practice" could be explanation, demos, etc. I also like short and sweet.

My 2 cents.

**Comment by fablio-work** [comment]
excellent point on best practices being a general term applicable to a broad array of topics...
agreed, "examples" is a fitting choice

**Comment by UCSB-jcolo** [comment]
Thx
I like:
http://ucsb-wsg.github.io/best-practice

James

**Comment by loganfranken** [comment]
I thought I was seeing a quorum for "/examples" so I went with that in my pull request; I'm totally open to other options, though!

(So please feel free to deny the pull request)

**Comment by tenken** [comment]
I will change this to examples after all the feedback. Although to my knowledge this requires I change the repository name to "examples" from "best-practice-examples".  If anyone was linking to this repository directly you will have to fix your Remote configuraiton.

**Comment by garster** [comment]
@tenken GitHub redirects the Browser viewing, but not sure about Git client remotes. I have renamed repos in the past for ARIT and things work out fine.

**Comment by tenken** [comment]
Alright, I'm now confused. We want the webguide to have "best-practice-examples" as a page? but the actual repository name dictates what that URL for the left sidebar in the webguide will be .... right now that repository name is "examples". So, while I accepted the Revert I'm thinking I should not have? Or will this page be filled out with links to various examples include our current examples at:
http://ucsb-wsg.github.io/examples/

**Comment by loganfranken** [comment]
Yeah, sorry, I probably made this confusing:

We _do_ want an intro page:
http://ucsb-wsg.github.io/best-practice-examples/

It will have some content that will contextualize and introduce the examples, like the old page (http://www.ucsb.edu/webguide/best-practice-examples).

So now we have:

**Intro page:** http://ucsb-wsg.github.io/best-practice-examples/
**Live best practice example:** http://ucsb-wsg.github.io/examples/

I think we're good to go, unless anyone's unhappy with those URLs.

**Comment by loganfranken** [comment]
(Another missing detail: I'll create a separate issue/pull request to fill out the content for the intro page)

**Comment by tenken** [comment]
Ok I understand now. I will close this issue as the url conflict is resolved. We'll make a new issue or just supply a pull request for the content.
