### ISSUE TITLE
Including Wiki Articles

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#251]
We have a few wiki articles on a number of topics:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki

Do we need some plan to move these articles into the Guide?

**Comment by garster** [comment]
It does not really make sense to have both a guide 'website' and this GitHub Wiki. I agree with @loganfranken.

**Comment by loganfranken** [comment]
I'll go ahead and make an issue for each wiki page.
