### ISSUE TITLE
Update mailing list references

### ISSUE THREAD

**Issue by dsaludares** [UCSantaBarbara/webguide#257]
http://webguide.ucsb.edu/contact/
Add section for joining mailing list, short description, and language such as:
"To join the UCSB-Web Mailing List, send a message to the co-chairs at wsg-chairs@connect.ucsb.edu"

Update links in these sections
http://webguide.ucsb.edu/about/
Footer

**Comment by garster** [comment]
@dsaludares how's this?

```
### Join Mailing List

The UCSB-Web Mailing provides a forum for UCSB Web professionals to exchange 
information about web design, development, best practices, and other 
web-related topics at UCSB. Web Standards Group meeting and event notices are 
also distributed via this list.

To join the UCSB-Web Mailing List, send an email to the co-chairs at 
[wsg-chairs@connect.ucsb.edu](mailto:wsg-chairs@connect.ucsb.edu).
```

**Comment by dsaludares** [comment]
That sounds good, @garster !

Do we want to say "UCSB-Web Mailing provides" or "UCSB-Web Mailing List provides"?

Also, since Web is capitalized in "UCSB Web professionals," should it be capitalized in "web design" and "web-related topics"?

Thanks!

**Comment by garster** [comment]
I lowercased Web on purpose. It's not a proper noun, just a noun. We should 'fix' this sitewide.
```
### Join Mailing List

The UCSB-Web Mailing List provides a forum for UCSB web professionals to exchange
information about web design, development, best practices, and other
web-related topics at UCSB. Web Standards Group meeting and event notices are
also distributed via this list.

To join the UCSB-Web Mailing List, send an email asking to subscribe to the
co-chairs at [wsg-chairs@connect.ucsb.edu](mailto:wsg-chairs@connect.ucsb.edu).
```
