### ISSUE TITLE
Consider Incorporating Wiki Page: "Accessible Document Tips"

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#263]
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Accessible-Document-Tips

**Comment by loganfranken** [comment]
I think this is actually already covered in the guide:
http://webguide.ucsb.edu/web-accessibility/#prefer-html-over-non-html-documents

That paragraph links to the Adobe accessible PDF guidelines:
https://www.adobe.com/accessibility/pdf/pdf-accessibility-overview.html

Which links to the Microsoft Enable accessibility website:
https://www.microsoft.com/en-us/accessibility/

I'd vote to actually close this issue and remove the wiki page since I like the idea of us pointing to other resources, but I'm open to whatever the group thinks is best.

**Comment by loganfranken** [comment]
Any thoughts on this?

**Comment by dsaludares** [comment]
I like the idea of pointing to other resources as well.

@garster What do you think? Shall we close this issue and remove the wiki page as Logan suggests?

**Comment by loganfranken** [comment]
Hey there!

Any updates on this? Should we tag it for discussion at a future meeting?

**Comment by garster** [comment]
I agree.

**Comment by garster** [comment]
Wiki page is deleted. Closing issue

**Comment by loganfranken** [comment]
Pasting the contents of that page (just in case):

--

Often times websites contain content that is not purely HTML or CSS. Sometimes digital documents must be distributed on a website in Adobe PDF, Microsoft Word, or other proprietary format. In these cases, while the content is not HTML-based, an effort can still be made to create content that is accessible.

Creating Accessible Documents from a Word Processing Application

When using a Word Processing application such as Microsoft Word, we recommend that the content author attempt to make use of styles or headings within your documents.

While a Word Processing application may seem like a simple tool, serious study must be undertaken to fully learn its appropriate use.

For example, content authors will often bold text to be seen as headings or use tables as a means to create fake visual columns within content—these are workflows that are to be avoided as they lead to inaccessible documents.

A comprehensive walk-through of creating accessible digital documents is beyond the scope of this document but there are numerous examples available online. For general tips, view a slideshow presentation by the AEGIS Project - Open Accessibility Everywhere group.

Creating a PDF from a Digital Document

Microsoft Office to PDF Workflow

For Office 2000-2003, 2007: either use Adode Acrobat or the Microsoft PDF add-in for Word to convert document to PDF.

For Office 2010/2013/2016: 32-bit alone, or 32-bit with Acrobat X, XI, or DC add-in (on 32-bit or 64-bit Windows)

In Office 2010/2013/2016, use the Check Accessibility tool found in the menu: File > Info > Check For Issues > Check Accessibility. Then resolve any errors or warnings provided by Word.
Acrobat ribbon > Preferences > Settings tab: a. check Enable Accessibility and Reflow with Tagged PDF b. check Enable Advanced Tagging (in Word 2010, this setting is on the Word tab) c. Advanced Settings button > Font section > i. Check + set Subset Embedded Fonts When Percent ... = 1% ii. empty the Never Embed list
Acrobat ribbon > Create PDF
Acrobat Pro > Tools > Action Wizard > Make Accessible Wizard > "Set Open Options" and "Set Tab Order Property"
For PDF/UA compliance (or a more accessible file), add a Document tag as the root element above Sect, fix remaining issues flip the PDF/UA identifier (using Acrobat Pro).
PowerPoint to PDF workflow

Get your master slides perfect first (or use an accessible base PowerPower pre-existing template) for reading order and alternative text (see notes section of this page for David's recipe).
Run Office 2010/2013/2016 Windows Accessibility Checker using File > Info > Prepare for Sharing > Check Accessibility..._. Resolve any errors, warnings and tips.
Export to PDF using File > Save & Send. a. In PowerPoint 2013/2016 this is the Create PDF/XPS button. b. Under Options uncheck Bitmap and check Accessibility.
Test with Acrobat Pro Full Accessibility Checker.
Adobe InDesign to PDF workflow

Adobe InDesign supports PDF tags subset. To maximize accessibility:

Add alt text/figures to images using Object > Object Export Options

Add tags to styles using Paragraph Styles > Export Tagging

Anchor images in the text flow

Use the Articles panel to define content order

Use bookmarks, table of contents, hyperlinks and cross-references as needed

Add Document Title to File info

export using the following options:

Creative Suite 5.5: PDF interactive, Buttons and Media = include All, check Create Tagged PDF

Creative Suite 6 and Creative Cloud: i. If your document contains forms, buttons, audio, video or animation then follow this workflow:

File > Export > Save As Type: PDF interactive, Forms and Media = include All, check Create Tagged PDF, check use Structure for Tab Order.
ii. Else, use File > Export > Save as Type "Adobe PDF (Print)" and check: Create Tagged PDF, check Books, check Hyperlinks, with Advanced > Subset Fonts when Percent of Characters Used is Less Than 0%.

iii. Options (i) and (ii) differ in that (i) gives many more settings unrelated to accessibility, and still offers bookmarks and/or hyperlinks if you need them. The tradeoff is only that you will loose the functionality (though optionally not the appearance) of any interactive elements.
Then within Acrobat Pro take this PDF and use an Action Wizard to perform the following tasks:

Pages pane > all > Page Properties > Tab Order = Use Document Structure
File > Properties > Advanced > Language
File > Properties > Initial Vie > Show Document Title
run Accessibility > Full Check
Adobe Illustrator to PDF Workflow

There is no alternative text or other such structures for accessibility, but:

Group items into objects that would deserve to be one figure.
File > File Info > Document Title
File > Save As > Save as Type = Adobe PDF, select Save
set Adobe Preset = High Quality Print
set Advanced > Subset Fonts When Percent of Characters use is Less Than = 0%
choose the Save PDF button.
Then perform all other PDF creation steps from within Acrobat Pro:

Pages pane > all > Page Properties > Tab Order = Use Document Strcture
File > Properties > Advanced > Language
File > Properties > Initial View > Show Document Title
run the Accessibility > Full Check and amend any issues.
