### ISSUE TITLE
Consider Incorporating Wiki Page: "Identify Technologies Used on a Website"

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#267]
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Identify-Technologies-Used-on-a-Website

**Comment by loganfranken** [comment]
I actually think it makes sense for this to stay within the wiki: these tools aren't necessary for following web best practices, but they are definitely useful.

What are all of your thoughts?

**Comment by loganfranken** [comment]
Any thoughts on keeping this in the wiki?

**Comment by dsaludares** [comment]
I agree with @loganfranken .  Being able to identify the technology used on a website is helpful, but it's not needed to follow web standards.  @garster , what do you think?

**Comment by loganfranken** [comment]
I'm going to go ahead and close this issue and leave this article in the wiki as-is, but I'm totally open if someone else feels differently!
