### ISSUE TITLE
Consider Incorporating Wiki Page: "Image Replacement"

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#268]
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Image-Replacement

**Comment by loganfranken** [comment]
Hmm, I'm debating this with myself: image replacement is a best practice I personally follow and it _does_ create a cleaner, more semantic HTML document, but I don't know if it should really be recommended as a standard in the guide.

I'm leaning towards removing it from the wiki. Thoughts?

**Comment by dsaludares** [comment]
I'm not sure about this one.  The Office of Public Affairs is encouraging us to use their new logo lock-up system.  Showing how to use title text and replace it with an image is a helpful example, especially now that we're all going to get these new logo lock-up images for our departments/divisions.  @garster , what do you think?

**Comment by loganfranken** [comment]
I agree with you, @dsaludares! Just submitted a PR for this update; thanks!

**Comment by garster** [comment]
This is a practice I have never heard about. I have strived to use text-based headers for a long time now, but ya this would be super useful for the the "lock-ups" (marketing speak? Need to look that up. Just like Hero image!)
