### ISSUE TITLE
Consider Incorporating Wiki Page: "Markup and Styling"

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#269]
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Markup-and-Styling

**Comment by loganfranken** [comment]
I would vote to leave this as-is _unless_ we wanted to incorporate these links into the actual content of the Web Guide.

There was concern in the past that including links to blog posts or other "unofficial" websites could be seen as an official UC endorsement of those websites as well as support for adjacent content on those websites (e.g. offensive comments on the blog posts).

**Comment by loganfranken** [comment]
Any thoughts on this one?

**Comment by dsaludares** [comment]
I think we should definitely avoid linking to any potential offensive comments on blog posts. What do you think, @garster ?

**Comment by loganfranken** [comment]
I'll leave this as-is in the wiki; thanks @dsaludares!
