### ISSUE TITLE
Add HTML5 placeholder text to Search Box

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#27]
I recommend we add HTML5 placeholder text to the search box on the webguide that says something like _Search this website_.

On HTML5 Placeholder attribute:
http://www.w3schools.com/tags/att_input_placeholder.asp

This is slightly an accessability request, but it is a minor fix (I hope) that will not impact legacy browsers with it's addition.

**Comment by loganfranken** [comment]
Could we add the label to mark this as something to discuss at the next WSG meeting?

**Comment by ilessing** [comment]
Yes, let's do add placeholder text to the search box.
