### ISSUE TITLE
Consider Adding Topic: Best Practice Example favicons

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#285]
See #265 and #58

**Comment by loganfranken** [comment]
Hey there!

Alright, Public Affairs provided us a favicon in #85:
https://github.com/UCSantaBarbara/webguide/issues/85#issuecomment-246480114

But I don't know if it's up-to-date w/ the latest Graphic Identity standards. Does anyone know if we have an updated favicon we're supposed to use?

**Comment by garster** [comment]
Yes I do! It's the social media square graphic. Let me dig up the email so we can use the explanation of the exception for favicon. Also there are a ton more "icons" now then use favicon, we should spell those out and supply them. I'll work on it. I've assigned this issue to me.

**Comment by dsaludares** [comment]
Thanks, @garster , for taking this on!

Public Affairs created a new "Web Assets" folder in their Visual Identity Guidelines and Assets share: https://ucsb.app.box.com/v/visual-identity

The Web Assets folder is under Logos and contains the favicon, but there's no explanation for usage.

**Comment by garster** [comment]
And we need to think about modern usage that uses larger graphics in standard formats. See https://www.kylejlarson.com/blog/adding-an-icon-for-iphone-ipad-android-to-your-website/

**Comment by loganfranken** [comment]
Closing this since the Best Practice Example isn't coming over in the migration
