### ISSUE TITLE
Consider Adding Topic: Embedding HTML5 video

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#292]
See #265

**Comment by loganfranken** [comment]
Should we close this one? I'm not sure what kind of value we can provide over basic instructions on embedding HTML5 video: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by garster** [comment]
I second @loganfranken.

**Comment by dsaludares** [comment]
Closing per discussion
