### ISSUE TITLE
Consider Adding Topic: JavaScript Standards

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#293]
See #265

**Comment by tenken** [comment]
I vote we close this topic as outside the current focus of the guide.

**Comment by loganfranken** [comment]
I could go either way on this one!

**Comment by dsaludares** [comment]
Wouldn't this be opening up a can of worms as well?

**Comment by loganfranken** [comment]
Yeah, you're probably right, @dsaludares: especially because there are probably existing areas we could further expand on before delving into stuff like when to use which equality operator, whether or not you should use semicolons, etc.

I agree that we should close this one too.
