### ISSUE TITLE
Consider Adding Topic: UX (Usability and User Experience) Standards

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#294]
See #265

**Comment by loganfranken** [comment]
I vote to close this topic as it seems pretty broad (but I'm totally open!)

**Comment by loganfranken** [comment]
Any thoughts on this one?

**Comment by loganfranken** [comment]
I'm going to close this one, but please let me know if anyone wants to reopen it!

**Comment by dsaludares** [comment]
Thank you, @loganfranken !  Sorry for not responding sooner!  I've been on vacation and I'm trying to catch up...
