### ISSUE TITLE
Consider Adding Topic: Marketing Standards

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#295]
See #265

**Comment by loganfranken** [comment]
I feel like this topic is a little too broad for us and I vote to close this one, but I'd be interested in what you all think!

**Comment by garster** [comment]
I concur with @loganfranken 

I think we just say you should follow the guidelines at brand.ucsb.edu on https://webguide.ucsb.edu/ucsb-graphic-identity/

**Comment by dsaludares** [comment]
I agree with you both @loganfranken and @garster

**Comment by loganfranken** [comment]
Sounds good! I'll go ahead and close this! Thanks!
