### ISSUE TITLE
Consider Adding Topic: PHP Standards

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#296]
See #265

**Comment by tenken** [comment]
Where might such a section be added to the Webguide, as I'm not really seeing a place for all of these possibly new topics to be added into the menu structure.

My other concern on creating the content for the section, is that as a php expert -- what scope(s) should be covered in such directions. I imagine directions such as:

> Look to your projects platform guidelines, best practices and coding style when developing a PHP based site. Such platforms such as the Drupal CMS, Wordpress and others contain their own guidelines which are considered a best-practice to follow. For custom built applications it's recommended to follow the PHP-FIG guidelines.

... any thoughts on these ideas? -dg

**Comment by loganfranken** [comment]
Yeah, I actually don't think this should be added to the web guide at all.

While we _do_ touch on some concerns that are arguably server-side-focused (friendly URLs, e-mail address contact forms, character encoding headers, etc.), I think the focus of the guide is primarily front-end standards and we're going to open a can of worms trying to tackle standards for server-side languages and frameworks.

Having said that, I'm totally open to what the group thinks is best.

**Comment by tenken** [comment]
I vote we close this topic as outside the current focus of the guide.

(if I could I would label this as "invalid" maybe to easily reference these issues in our next WSG meeting)

**Comment by dsaludares** [comment]
I like the directions that @tenken lists above. For the Drupal coding standards, we could link to https://www.drupal.org/docs/develop/standards/coding-standards and to similar documentation for WordPress.

But, @loganfranken is right, we would be opening a can of worms by including PHP standards in the Web Guide. I'll label this as "invalid."
