### ISSUE TITLE
Consider Adding Topic: Google Analytics Standards and Resources

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#299]
See #265

**Comment by loganfranken** [comment]
We've got a note recommending the use of Google Analytics (or some analytics tracking system) and a link to the UCSB procedures document on using it:
https://webguide.ucsb.edu/browsers/

Do we feel we need more than that in the guide?

**Comment by loganfranken** [comment]
I'll go ahead and close this but let me know if anyone disagrees!

**Comment by dsaludares** [comment]
Thank you as always, @loganfranken !
