### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#3]
The Web Standards Guide should have a responsive design to fit in line with our recommendations (http://www.ucsb.edu/webguide/viewport-dimensions).

**Comment by loganfranken** [comment]
URL of the page in the GitHub-hosted repo:
http://ucsb-wsg.github.io/viewport-dimensions/

**Comment by tenken** [comment]
A meeting was held June 11, 2015 with Public Affairs going over a responsive update to appear similar as the UCSB homepage. Web Designers from Student Affairs and Life Sciences have shown interest in helping in the redesign.

Public Affairs will meet with the designers wanting to help to try to get a reusable style guide in place for these sites using current web design tools. Once this meeting has occurred hopefully we'll get some feedback to the WSG.

**Comment by tenken** [comment]
Someday this will look good:
http://design.google.com/resizer/#url=http%3A%2F%2Fwebguide.ucsb.edu

It would be a nice treat to like embed the Google preview tool into the content of 1 our webguide pages as an iframe showing the above url in the page to visually illustrate what RWD is. Or at the least possibility link to this example from our RWD description page.

I believe the IFRAME approach they use here is exemplified elsewhere:
http://codepen.io/NobodyRocks/pen/vLRNvb

**EDIT:**

Whoa, the Resizer thing is all done in javascript and included onto the page ... hmmm.
