### ISSUE TITLE
Consider Adding Topic: Source Control Standards and Resources

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#300]
See #265

**Comment by tenken** [comment]
I vote we close this topic as outside the current focus of the guide.

Although, I actually think this topic is more tricky than just backend development practices. I think it would be helpful to contributors to know what _not_ do to when commiting to the project, such as include large binary files into the repo or other such anti-patterns. The repo is the history of the project and ideally someone is overseeing it's maintenance. But maybe that's just the current Co-chairs.

**Comment by loganfranken** [comment]
Yeah, I agree: I definitely see value in continuing to evolve our guidelines/best practices for contributing to the guide itself (https://github.com/UCSantaBarbara/webguide/blob/master/README.md), but I don't think it's within our scope to provide general standards for source control.

**Comment by dsaludares** [comment]
Agree.
