### ISSUE TITLE
Replace UC Santa Barbara workmark in header with new version in white.

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#307]

**Comment by garster** [comment]
So I attempted this but found that the image replacement technique we use for the main heading does not work for SVG. Our current SVG must be sized for our site where the one I put in there does not.

![image](https://user-images.githubusercontent.com/4443025/46805941-2b5b1280-cd1b-11e8-9cd1-c1051d6b0b1e.png)

I was googling the issue and ran across [Do We Still Need Image Replacement?](http://www.loganfranken.com/blog/1244/do-we-still-need-image-replacement/) by @loganfranken 

I have not read the entire post, but maybe he can chime in a help me out?

**Comment by ericmayes** [comment]
It will indeed work with the SVG inline code, it just needs to be sized and color filled via CSS as follows:

width: auto;
height: 24px;
fill: #fff;

**Comment by ericmayes** [comment]
Also use this to select it: 
.navbar-brand svg{
width: auto;
height: 24px;
fill: #fff;
}

**Comment by garster** [comment]
Cool. I have spent hours trying to get everything set up to compile the CSS and it's failure after failure. npm, ruby, python, now it can't compile some node modules. I think this thing just needs an overhaul!

**Comment by ericmayes** [comment]
Why don't we just spin up a new pantheon version?

**Comment by rvizena** [comment]
Only took a year, but a pantheon version is currently under development :)

**Comment by rvizena** [comment]
Confirming new site has correct branding for wordmark. Closing
