### ISSUE TITLE
Add instructions for using UCSB Web Fonts

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#327]
Instructions are coming soon for usage of the UCSB web fonts. It would be great either house or reference those instructions here

May I suggest it's own page under "Graphical Presentation" if the instructions live on the webguide, or just a section under UCSB Graphic Identity if the instructions live on a different site.

**Comment by garster** [comment]
Today I need this. :-( Gotta go hunt for it

**Comment by garster** [comment]
Here is the instructions page http://www.ia.ucsb.edu/webfonts/

So we should not duplicate it.

**Comment by dsaludares** [comment]
Let's ask Alex if it is OK to point to http://www.ia.ucsb.edu/webfonts/

He may want to put it in the Visual Identity Guidelines and we can link to it from there.

**Comment by dsaludares** [comment]
At the WSG meeting on September 4, 2018, it was decided to wait until web font usage information was posted on [brand.ucsb.edu](http://brand.ucsb.edu) instead copying content from or linking directly to http://www.ia.ucsb.edu/webfonts/ in the web guide.

**Comment by loganfranken** [comment]
They've got this published now:
https://brand.ucsb.edu/tools-and-templates/web-fonts

@garster I think we can close this, right?
