### ISSUE TITLE
Set up HTTPS for webguide.ucsb.edu

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#328]
Github finally supports https for custom domains. See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ for details.

**Comment by garster** [comment]
Looks like it is automatic. All we need is the enforce https setting turned on, and any links updated.

**Comment by dsaludares** [comment]
This is awesome!

**Comment by tenken** [comment]
Various sub links in the site such as /policies when clicked from the site menu bar goto a non-https version of the page.

I assume the yaml configuration for the site may need a flag to denote https enabled linking ... Or examine the source code for hardcoded http links.

**Comment by garster** [comment]
There is a URL setting in https://github.com/UCSantaBarbara/webguide/blob/master/_config.yml that references http://

**Comment by tenken** [comment]
On a phone, clicking on Site Map in the footer goes here, but in http mode:
https://webguide.ucsb.edu/site-map

From then on any links clicked in the site map stay in http.
