### ISSUE TITLE
"x" and "y" GET Parameters Getting Sent Along w/ Search Form Submit

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#343]
If you use the search form, the GET request includes "x" and "y" URL variables:
https://webguide.ucsb.edu/search/?query=analytics&x=0&y=0

I _think_ this is happening because an `input type="image"` is being used. We should double-check that this is the expected use of that type of input.

**Comment by garster** [comment]
This is normal behavior.

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/image#Using_the_x_and_y_data_points

**Comment by loganfranken** [comment]
Yup, as @garster says, the MDN docs say this is the correct use of the input: "<input> elements of type "image" are used to create graphical submit buttons". Closing this out! Thanks!
