### ISSUE TITLE
Simplify development

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#345]
I always struggle with development of this site. It needs some love badly.

I am going to submit a PR with these changes, basically going to vanilla Jeykll. If you'll like it and accept it I will be able to do much more development.

- Remove dependency on Gulp to simplify the build stack.
- Jekyll has build-in SASS support, let Jekyll handle it.
- Don't minify css and js (the site gets only a few visits per month, this is overkill and not worth the complexity IMO).

Later I might set up Webpack (the current hotness for building sites) but for now just going to plain Jeykll will help at a lot.

**Comment by dsaludares** [comment]
Thank you, @garster !!!  I'm happy that you're giving this site some love!
