### ISSUE TITLE
Remove references to unsupported browsers

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#347]
There is some content that talks about IE 8.

As of 1/2016 Only IE 11 was supported by Microsoft. All previous versions are unpatched. 
https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

We should not mention obsolete browsers. I will collect a list of content.

**Comment by loganfranken** [comment]
@garster I think your PR fixed this, right? (Thanks!) We can close this one, right?

**Comment by loganfranken** [comment]
@sbbeachvball @BwolfUCSB It looks like @garster already fixed this one, so I think we're good to close this issue!

**Comment by loganfranken** [comment]
@garster @sbbeachvball @BwolfUCSB I think this one can be closed!

**Comment by ghost** [comment]
Closed.
