### ISSUE TITLE
Restructure Site

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#353]
I think the structure of the website is starting to make less and less sense (I think I'm the one who came up with the current hierarchy, so it's on me 😅).

For example: the HTML section contains some CSS, the Header section contains information about Resources, and so on. Unless you're reading through the entire guide, it can be confusing to know where to go for a specific topic.

There's also a number of sections that are simply brief summary paragraphs, like UCSB Graphic Identity, Viewport Dimensions, and Frameworks.

This could be an opportunity to think through the future of the Web Guide: does it still provide value as a standards reference? Since the Web Guide can't contain everything, how do we distinguish between the content of the guide and general resources online? How often do we, ourselves, use the Web Guide? What do we use it for?

With the new UC branding and the need to update our Best Practices template, could the Web Guide evolve into a UI framework or pattern library that would document standards alongside those individual components (e.g. maybe a "Forms" section would show how to properly mark up a form, how to make it match UC branding, how to make it accessible, how to make sure it meets policy standards)?

Just some thoughts!

**Comment by garster** [comment]
I am *slowly* working on a Bootstrap 4 revamp of the UI (Get rid of YAMM). The UI would be 95% the same, but I did notice the structure was a big confusing and a lot is repeat of what should be common knowledge (Maybe that's a good thing).

I would love to be on a sub-committee in the new year that reviews and reorganizes the site.

**Comment by loganfranken** [comment]
It doesn't look like there's a ton of interest in this topic, so I'll go ahead and close it! Someone else can feel free to reopen!
