### ISSUE TITLE
Browsers Page > Broken Piwik Link

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#359]
The "Piwik Analytics Platform" link on the Browsers page (https://webguide.ucsb.edu/browsers/) doesn't go anywhere. Does the link need to be updated? Or is this no longer a service they offer?

**Comment by garster** [comment]
It is GONE from the ETS site https://www.ets.ucsb.edu/services-grid/

My used it but we switched over to Google a while back. I bet they still run it, but do not offer it to new clients.

I say remove any reference to it.

**Comment by garster** [comment]
I checked, I can still login to https://analytics.ets.ucsb.edu/ and there is some data so I have some code lingering somewhere.

**Comment by fablio-work** [comment]
FWIW: piwik changed it's name to Matomo.  https://matomo.org
