### ISSUE TITLE
Rename "Best Practice Examples" Repo

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#36]
To complete the work for #34, the "Best Practices Examples" repo needs to be renamed _again_ (sorry) to "templates" so that it will live at: http://ucsb-wsg.github.io/templates/

Totally open to any alternative suggestions for the name!

**Comment by tenken** [comment]
I changed the repository name. Hmm, I'm not sure but something broke :/

I thought the most recent merge request restructured these pages ... maybe I didnt look at them close enough!

**Comment by loganfranken** [comment]
I _think_ things are good:
http://ucsb-wsg.github.io/best-practice-templates/
http://ucsb-wsg.github.io/templates/
http://ucsb-wsg.github.io/examples/

It looks like http://ucsb-wsg.github.io/examples/ is giving a 404 (which is what you're talking about, right?).

I would imagine that GitHub's redirect rules just need to catch up. Either they will fix themselves in a bit or we'll need to push through an update to force them to update.

I have an update in mind so maybe we can just try the latter and see what happens.

**Comment by loganfranken** [comment]
Looks like the update did it! Everything's fixed!

(I think we're good to close this one)
