### ISSUE TITLE
Favicon Requested Over HTTP

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#362]
The favicon URL is HTTP, but the website itself is HTTPS; this will cause browsers to block the download of that favicon (or display an error message)

**Comment by ilessing** [comment]
Was this perhaps fixed already by some other commit?

when I ran the https://webguide.ucsb.edu/ through the [missing padlock](https://www.missingpadlock.com/) tool no mixed content issues were reported.

Also when I load the site the browser lock icon is locked.   

ref [_includes/head.html](https://github.com/ucsb/webguide/blob/9529d3e243c174663f9599e85155134fc3a12a6c/_includes/head.html#L22) 

![2020-07-07 Missing Padlock-5-31](https://user-images.githubusercontent.com/275899/86861107-2277ac00-c07b-11ea-8271-a9cfa8577274.png)

**Comment by loganfranken** [comment]
Hey @ilessing!

Nah, it looks like it's still making the request (although it's got the fallback favicons, so it ends up working out):

![image](https://user-images.githubusercontent.com/1024444/86868503-ab95df80-c089-11ea-85d8-1629722e6e37.png)

![image](https://user-images.githubusercontent.com/1024444/86868522-b3ee1a80-c089-11ea-8cdb-efe441ed5ee4.png)

**Comment by loganfranken** [comment]
This is still a bug in the current web guide, but it's fixed in the new web guide, so I'm closing.
