### ISSUE TITLE
Bootstrap Example on "Frameworks" Page is Incorrect

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#363]
The Bootstrap example on the "Frameworks" page:
https://webguide.ucsb.edu/frameworks/

Doesn't match the current example from Bootstrap:
https://getbootstrap.com/docs/4.1/components/navs/#tabs

**Comment by garster** [comment]
4.1 is old. The "current" is 4.3
https://getbootstrap.com/docs/4.3/components/navs/#tabs

**Comment by loganfranken** [comment]
Augh, sorry: thanks @garster!

(To be clear to anyone reading this issue: even though I pointed to the wrong version, the example still needs updating)
