### ISSUE TITLE
Policy Toolkit Link is Broken

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#365]
This link for the "UCOP Policy Toolkit" on the Policies page is broken:
http://www.ucop.edu/ethics-compliance-audit-services/policy/policy-toolkit.html

**Comment by ghost** [comment]
Logan

Did you track down the new link?

B

Brian Wolf
Web Designer / Developer
Life Sciences Computing Group
UC Santa Barbara

Phone: 805.893.5932
Email: brian.wolf@lscg.ucsb.edu
Portfolio: webdesign.lscg.ucsb.edu

**Comment by ghost** [comment]
Logan

Did you find a new link?

Brian Wolf
Web Designer / Developer
Life Sciences Computing Group
UC Santa Barbara

Phone: 805.893.5932
Email: brian.wolf@lscg.ucsb.edu
Portfolio: webdesign.lscg.ucsb.edu

**Comment by loganfranken** [comment]
Hey @BwolfUCSB!

Nah, just opening the issue for now and will research later if no one else gets the chance.

**Comment by ghost** [comment]
Grazie!

Brian Wolf
Web Designer / Developer
Life Sciences Computing Group
UC Santa Barbara

Phone: 805.893.5932
Email: brian.wolf@lscg.ucsb.edu
Portfolio: webdesign.lscg.ucsb.edu
