### ISSUE TITLE
Adaptive Software Provider Links

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#368]
The Adaptive Software Provider links are no longer accurate:
https://webguide.ucsb.edu/web-accessibility/

**Comment by jeffpignataro** [comment]
The JAWS link makes more sense to go to https://www.freedomscientific.com/products/software/jaws/. The other two seem accurate though.

**Comment by loganfranken** [comment]
It looks like the "Ai Squared" link goes to some place called "ZoomText"?

**Comment by jeffpignataro** [comment]
ZoomText is the product which Ai Squared produces.

**Comment by loganfranken** [comment]
Ahh, I see it now! Thanks @jeffpignataro!

**Comment by loganfranken** [comment]
This is no longer an issue; closing!
