### ISSUE TITLE
Broken Link: "Section 504 of the Rehabilitation Act of 1973"

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#369]
The "Section 504 of the Rehabilitation Act of 1973" link is broken:
https://webguide.ucsb.edu/web-accessibility/

**Comment by jeffpignataro** [comment]
Looks like it's moved to [here](https://www.dol.gov/agencies/oasam/civil-rights-center/statutes/section-504-rehabilitation-act-of-1973). I'll update it.
