### ISSUE TITLE
Favicon is broken

### ISSUE THREAD

**Issue by jeffpignataro** [UCSantaBarbara/webguide#377]
Head.html references a favicon - https://www.ucsb.edu/images/favicon.ico - which doesn't exist.

**Comment by jeffpignataro** [comment]
Also, the current favicons don't follow the [new branding](https://brand.ucsb.edu/visual-identity/university-marks).

**Comment by monsij** [comment]
https://github.com/ucsb/webguide/blob/9529d3e243c174663f9599e85155134fc3a12a6c/_includes/head.html#L13

I guess this line can be safely removed.
