### ISSUE TITLE
plan content migrate to 2020 WSG drupal8 site

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#384]
## Issue

Discussed in the May 05, 2020 meeting co-chairs and wsg members can brainstorm and collaborate on what content to move, or not move from https://webguide.ucsb.edu/ to https://dev-webguide-ucsb-edu-v01.pantheonsite.io/

Prior WSG meetings noted that some content on the webguide is may now be outdated or require revision. This is now a time for attendees to help to perform some maintenance of this content.

The current proposed top-level site structure is of the drupal site is:
* Content
* Design
* Development
* Security
* Accessibility
* Resources
* additionally a Private Member Area to include meeting minutes and co-chair related procedural documentation.

As a WSG member if you feel you can make a positive contribution to this content maintenance or discussion please chime in!

### Contributing a content update
* contact the co-chairs at wsg-chairs@connect.ucsb.edu and request a Drupal user account for editorial access to the site to help create the updated page content. Please leave your content unpublished and co-chairs or the group will approve the content at the next meeting.

### Pre-existing site pages on webguide.ucsb.edu
| Task Completed | Legacy Page | New URL | Collaborator | Issue\#|
|----|----|----|----|----|
| :heavy_check_mark: | https://webguide.ucsb.edu/about/ | [link](https://dev-webguide-ucsb-edu-v01.pantheonsite.io/about-wsg) | Logan | |
| :heavy_check_mark: | https://webguide.ucsb.edu/best-practice-templates/| Not Moving | TBD | |
| :heavy_check_mark: | https://webguide.ucsb.edu/browsers/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/development <br><br> https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources | Logan | #388 |
| :heavy_check_mark: | https://webguide.ucsb.edu/campus-resources/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources <br>with new Gauchocast Panopto embeds | Logan,David | #390 |
| | https://webguide.ucsb.edu/web-standards-checklist/| TBD | TBD | |
| :heavy_check_mark: |https://webguide.ucsb.edu/contact/| [link](https://dev-webguide-ucsb-edu-v01.pantheonsite.io/contact) | Ryan | #392  |
| :heavy_check_mark: |https://webguide.ucsb.edu/css/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/css | Logan | #393 |
| :heavy_check_mark: |https://webguide.ucsb.edu/email-addresses/| Not Moving | TBD | #394 |
| :heavy_check_mark: |https://webguide.ucsb.edu/examples/| Not Moving | TBD | #387 |
| :heavy_check_mark: |https://webguide.ucsb.edu/favicon-and-touch-icons/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/favicon-and-touch-icons | Logan | #397 |
| :heavy_check_mark: |https://webguide.ucsb.edu/footer/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/design/footer | dgurba | #389 |
| :heavy_check_mark: | https://webguide.ucsb.edu/frameworks/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/development/css | Ryan | #399  |
| :heavy_check_mark: | https://webguide.ucsb.edu/header/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/development/html | Logan | #400 |
| :question:  | https://webguide.ucsb.edu/html/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/development/html | Logan | #401 |
| :heavy_check_mark: | https://webguide.ucsb.edu/policies/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources/policies | Ryan | |
| :heavy_check_mark: | https://webguide.ucsb.edu/resources/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources | Logan,David | #390<br>#395 |
| :heavy_check_mark: | https://webguide.ucsb.edu/seo/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/content/seo-search-engine-optimization | Ryan | #407 |
| | https://webguide.ucsb.edu/site-map/| TBD | TBD | |
| :heavy_check_mark: | https://webguide.ucsb.edu/ucsb-graphic-identity/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/design/uc-santa-barbara-branding | Ryan | #410  |
| :heavy_check_mark: | https://webguide.ucsb.edu/urls/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/development/domains-urls | Ryan | #411 |
| | https://webguide.ucsb.edu/viewport-dimensions/| TBD | TBD | |
| :heavy_check_mark: | https://webguide.ucsb.edu/web-accessibility/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/accessibility-0 | Eric M | #403  |
| :heavy_check_mark: | https://webguide.ucsb.edu/web-security/| https://dev-webguide-ucsb-edu-v01.pantheonsite.io/website-security | Ryan,Gary | #405 |
| | https://webguide.ucsb.edu/README-DEVELOPER.html| TBD | TBD | |
| | &mdash; | New Member Pages:<br>login page<br>attendance list (via GoogleSheets data)<br>history | Ryan,David | #396<br>#398 |

**Comment by loganfranken** [comment]
Sorry for the wait on a response!

I can just start working my way down this list: I'll start with the "About" page.

@tenken should I just create a separate GitHub issue for moving that particular page? Or did you want to keep it all in this thread? (I'm up for either)

Also, would it be possible to accept the existing PRs so we can have the latest content in the pages before we migrate them?

**Comment by tenken** [comment]
@loganfranken I have merged all pending PRs. If you'd like to make an issue per page that would be ok. Perhaps cluttering this single issue may put some contributors off ... Thanks for your input and time!

**Comment by tenken** [comment]
* add sections for Security, Accessibility to above table. for Eric and maybe Gary?

**Comment by ericmayes** [comment]
Sounds good. Moving the slack discussion / info for the a11y section here:

So far I had a few ideas I came up with a couple weeks back :
Siteimprove additions
Maybe a way to contact Siteimprove admin email without exposing the address
Automatic vs Manual testing and how automatic testing doesn't give you the entire picture
Guidelines additions
Something about using native elements whenever possible
Mention vendor requirements - a11y etc
Policies
Benefits of a11y (something I saw UCSF list on their site)
Campus Contacts - needs updating, I will at least update the new AT specialist
Also I noticed this page you can only get to via the breadcrumb, I love the Tim Berners-Lee quote I actually used that in a presentation on Accessibility history a couple years back when I showed a video clip of him at the Olympic games conveying that message. Just not sure the page is something we need to move to a menu item : https://dev-webguide-ucsb-edu-v01.pantheonsite.io/accessibility-0

**Comment by loganfranken** [comment]
FYI: As far as I can tell, we currently have an issue for every existing page of the web guide.

**Comment by rvizena** [comment]
@loganfranken Did you get a 504 error on page load? If so, Pantheon spins down sites that go inactive.  A couple browser refreshes should bring it back it up.

**Comment by loganfranken** [comment]
Hey @rvizena! Sorry, to be clear: I wasn't reporting an issue. Just saying that every page from the old guide has a corresponding migration issue here in GitHub (so once we close all the issues, we should have migrated everything over!)

**Comment by rvizena** [comment]
@loganfranken wow I really misunderstood your comment hahaha. 
I went ahead and updated this master list.  We really only have one or two things left. Let me know what you think about the Viewport Dimensions section. After that, we need to lockdown the CAS login + Member Menus and then we are ready to rock.  Thanks for the help thus far!

**Comment by tenken** [comment]
the wsg site is now all live for 1-2 months.
