### ISSUE TITLE
Don't Migrate "Best Practice Template" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#387]
#384 

**Legacy Page**
https://webguide.ucsb.edu/best-practice-templates/

**Location in New Hierarchy**
N/A

I actually vote that we remove this page altogether. Any thoughts?

**Comment by tenken** [comment]
sure, let's not move this page. And we'll note it at the next WSG meeting.

**Comment by rvizena** [comment]
Looking at what's present on that page, I would also move to remove completely.

**Comment by loganfranken** [comment]
It sounds like we're not moving this page, so I'll close this out.
