### ISSUE TITLE
Migrate "Browsers" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#388]
#384 

**Legacy Page**
https://webguide.ucsb.edu/browsers/

**Location in New Hierarchy**
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/development
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources

Here's my draft for the content we should migrate to the **"Development"(Overview) page**:

---

The Web Standards Group recommends that webpages be designed to work with the browsers and platforms that approximately 90% of your website’s visitors use.

---

Here's my draft for the content we should migrate to the **"Resources" page**:

---

## Analytics

Website maintainers should **use web analytics tools** to analyze traffic statistics for their site.

As of June 2015, UCSB policy allows the use of Google Analytics for tracking website visitor statistics. But, departments and entities using Google Analytics should abide by the [procedures](https://www.policy.ucsb.edu/files/docs/policies/clickthrough-guide.pdf) outlined by the announcement of campus support of Google Analytics and other click-through agreements.

**Comment by rvizena** [comment]
Draft looks good, Logan.  If you can add these in to the respective pages, that would be great. We will review at the July 7th WSG meeting. Thank you!

**Comment by loganfranken** [comment]
Thanks @rvizena!

Updated:
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/development
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources

**Comment by tenken** [comment]
* approved by wsg meeting.
