### ISSUE TITLE
Migrate "Footer" Page

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#389]
#384 

**Legacy Page**
https://webguide.ucsb.edu/footer/

**Location in New Hierarchy**
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/content/footer

Below is my draft for the content we should migrate to the **Footer Page**
* I omit migrating the footer markup that is a pre-HTML5 exaxmple as now the web is essentially HTML5 so DIVs with Aria labels are not needed anymore when we're trying to instill best-practices for developers. We can just recommend `<footer>` with use of an Aria role -- the current UCSB Web Theme does this out of the box.

-----
Each UCSB website must include a footer at the bottom of each webpage with the elements described in this section.

### COPYRIGHT
Include this standard form copyright notice as recommended by the UC Copyright Guide.
```txt
Copyright &copy; 2020 The Regents of the University of California, All Rights Reserved.
```
You may display the year of first publication or the current year using a server-side technology.

The notice format can be altered or omitted to fit your needs.

For more information about copyright requirements, visit UC Copyright FAQ: How do I put a copyright notice on my work?

### TERMS OF USE
Each footer should include a link to the UCSB Terms of Use. Each website can either link directly to the UCSB Terms of Use document or include the content from that document on their own page using a server-side technology.

If your organization needs to modify the Terms of Use document for a specific purpose, you should submit the modified version for approval to policy@ucsb.edu. If the Coordinator approves the modified content, the updated version can be used and a copy will be retained by Administrative Services.

### PRIVACY NOTIFICATION
All UCSB websites that collect personal information from visitors should include a link to the UCSB Privacy Notification. Anonymous information collected for the purpose of web analytics is not considered personal information. Similar to the Terms of Use, each website can either link directly to the UCSB Privacy Policy or include the content from that document on their own page using a server-side technology.

The link to either the UCSB Privacy Policy or the page with the included content should contain the word “privacy.”

If your organization needs to modify the Privacy Policy document for a specific purpose, you should submit the modified version for approval to policy@ucsb.edu. If the Coordinator approves the modified content, the updated version can be used and a copy will be retained by Administrative Services.

It is a good practice to also include a link to the privacy policy close to where a user is entering personal information. For example, a link to the privacy policy could be added to the top of a form that a user is filling out or next to where a user enters their username and password to log into a secure application.

### ACCESSIBILITY
Include a statement or link to a statement offering alternative content for those who cannot access your page:

```txt
If any of the material on this page is not accessible to you, please
<a href="mailto:webmaster@department.ucsb.edu">send us an email</a>
or <a href="/contact">contact us via our contact page</a>
and we will provide alternatives.
```
### LAST MODIFIED DATE (OPTIONAL)
Each web page may contain the date the last time the page was updated. The last modified date should appear in the following format: May 4, 2018 (no month or year abbreviation)

### CONTACT LINK
All websites should contain an email link or link to a contact form to contact someone within the organization about questions or concerns with the website.

### “CONTENTINFO” LANDMARK ROLE
The element containing the footer should be marked with the “contentinfo” ARIA role:
```html
<footer>
    <!-- Footer Content -->
</footer>
```
### FOOTER EXAMPLE
The following example includes all of the guidelines described above:
```html
<footer>
    Copyright &copy; 2020 The Regents of the University of California,
    All Rights Reserved
    <br>
    <a href="http://www.policy.ucsb.edu/terms-of-use/">Terms of Use</a> /
    <a href="http://www.policy.ucsb.edu/privacy-notification/">Privacy Notification</a> /
    <a href="/accessibility">Accessibility</a>
    <br>
    Last Modified May 4, 2020 /
    Questions or contacts? Please <a href="/contact">contact us</a>
</footer>
```

**Comment by tenken** [comment]
* look into removing the ARIA landmark recommendations. just leave HTML5 `<footer>` example. SiteImprove thinks they are "legacy" addons... revise for next meeting.

**Comment by loganfranken** [comment]
So, as far as I know, what's currently on the page tracks with the current W3C recommendations (https://www.w3.org/TR/wai-aria-practices/examples/landmarks/contentinfo.html):

* Use `role="contentinfo"` if it's a `div`
* Don't use `role="contentinfo"` if it's a `footer` (since it's redundant)

If we want to condense it down, I say we go with just:

```
<footer>
</footer>
```

**Comment by tenken** [comment]
@tenken complete this today.

**Comment by tenken** [comment]
@rvizena I have revised this page: https://dev-webguide-ucsb-edu-v01.pantheonsite.io/design/footer
* I limited the site supported languages via the ckeditor full_html options.
* I set the github colorscheme for all embedded code snippets.

Ideally we can have "plaintext" be an option for supported languages, but offhand I can't see how to set that without overriding some configuration values possibly via drupal code and the Ckeditor API.

**Comment by tenken** [comment]
## Make changes to site for CodeSnippets
```txt
.../2020/pantheon/webguide-ucsb-edu-v01 ⑂389-footer* $ 
git commit 
[389-footer a51fe50d8] Adjust codesnippet configuration.
 19 files changed, 513 insertions(+), 8680 deletions(-)
 delete mode 100644 .idea/inspectionProfiles/Project_Default.xml
 delete mode 100644 .idea/misc.xml
 delete mode 100644 .idea/modules.xml
 delete mode 100644 .idea/php.xml
 delete mode 100644 .idea/vcs.xml
 delete mode 100644 .idea/watcherTasks.xml
 delete mode 100644 .idea/webguide-ucsb-edu-v01.iml
 delete mode 100644 .idea/workspace.xml
 delete mode 100644 .lando.yml
 rewrite libraries/codesnippet/lib/highlight/highlight.pack.js (99%)
 copy libraries/codesnippet/lib/highlight/{highlight.pack.js => highlight.pack.js.old} (100%)
 create mode 100644 modules/custom/ucsb_webguide/ucsb_webguide.info.yml
 create mode 100644 modules/custom/ucsb_webguide/ucsb_webguide.module
 rewrite vendor/composer/autoload_classmap.php (99%)
 rewrite vendor/composer/autoload_static.php (96%)
```
* some items for UCSB Web Theme projects ideally are removed from upstream. Notably `.idea` folder and `.lando.yml` files as they are developer centric.
* created simple module to affect language changes, and modified codesnippet `libraries/codesnippet/lib/highlight/highlight.pack.js` file with limited set of language support for use on site https://highlightjs.org/download/
* prior to the `.pack` file update `coffeescript` was always applied to `plaintext` chosen language, the pack file update seems to have fixed that error.
* enabled custom module on site:
```txt
.../2020/pantheon/webguide-ucsb-edu-v01 ⑂389-footer $ 
lando drush @pantheon.webguide-ucsb-edu-v01.389-footer en ucsb_webguide -y

The following extensions will be enabled: ucsb_webguide
Do you really want to continue? (y/n): y
ucsb_webguide was enabled successfully.                              [ok]
```

The module maintainer has documentation on how to change supported languages https://www.drupal.org/project/codesnippet but the directions are incorrect. Added a comment to a D.org issue at https://www.drupal.org/project/codesnippet/issues/3021431#comment-13775893

### Example: https://389-footer-webguide-ucsb-edu-v01.pantheonsite.io/design/footer
### DEV: https://dev-webguide-ucsb-edu-v01.pantheonsite.io/design/footer

**Comment by tenken** [comment]
Merge later this week.

**Comment by tenken** [comment]
* 389-footer multidev merged in Dev.
* https://dev-webguide-ucsb-edu-v01.pantheonsite.io/design/footer  page updated with approved 389-footer example content.

/close
