### ISSUE TITLE
Migrate "Campus Resources" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#390]
#384 

**Legacy Page**
https://webguide.ucsb.edu/campus-resources/

**Location in New Hierarchy**
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources

I'm basically proposing we move what's already there, with a few caveats:

- Remove link to "GitHub Wiki" since it's not really used
- Reword the photography section, taking out the Tony Mastres link (https://ucsbphoto.photoshelter.com/)

-----------

### [UCSB IT Website](https://it.ucsb.edu/)

A launch pad to the information technology organizations that provide
infrastructure, applications, and services to support academic and business
activities at UCSB.

### [Github Issue Tracker](https://github.com/UCSantaBarbara/webguide/issues)

Any individual seeking clarification or with an inquiry regarding web standards or best practices is encouraged to post their inquiry in the Github Issues Tracker which is actively moderated by the WSG Co-Chairs and WSG members. Please note that the Github platform requires a user account, by participating on Github your inquiries and responses will be in the public domain. Please observe proper etiquette and be respectful of others.

### [UCSB-Web Mailing List](https://dev-webguide-ucsb-edu-v01.pantheonsite.io/about-wsg)

Provides a forum for UCSB web professionals to exchange information about web
design, development, best practices, and other web-related topics at UCSB. Web
Standards Group meeting and event notices are also distributed via this list.

### [Computer Support Forum (CSF) Mailing List](https://lists.noc.ucsb.edu/mailman/listinfo/csf)

Provides a means for UCSB computer support staff to exchange questions,
answers, and information in support of computing at UCSB.

### UCSB Campus Image Resources

The [UCSB Digital Asset Library](https://ucsb.webdamdb.com/
), hosted by WebDAM, is a resource available to all UCSB personnel, acting as a centralized location for high quality photography of the campus.

You also may hire [Instructional Development Photography Services](http://photo.production.id.ucsb.edu/) photographers to shoot on location or in their studio or contact the UCSB
[Cheadle Center for Biodiversity and Ecological Restoration (CCBER)](https://www.ccber.ucsb.edu)
for photographs.

### [UCSB API Developer Portal](https://developer.ucsb.edu/)

A portal for UCSB APIs, including documentation and an interactive tool for
testing.

**Comment by loganfranken** [comment]
Updated on the page:
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources

**Comment by rvizena** [comment]
@loganfranken This looks good, and I see this space growing as we develop the site and find more resources. Would like to discuss laying out this page with more Web Theme features w/ the blades, and your comfortability with designing these pages. I will provide example(s) for reference.

**Comment by loganfranken** [comment]
Hey @rvizena!

I'm open to redesigning the pages to match whatever examples you think are best!

**Comment by tenken** [comment]
* I have added a link to the WSG Gauchocast page and added 2 inline panopto embeds to the page. I have not created a full-fleded "Past Presentations" page as on the multi-dev yet. There was mixed group feedback on that.
  * see https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources

**Comment by rvizena** [comment]
Thanks for adding Panopoly content to this page - I like the 2 inline videos for now. We can link to the WSG Gauchocast page from here. I have styled up the blades for each Resource link.
