### ISSUE TITLE
Migrate "Checklist" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#391]
#384 

**Legacy Page**
https://webguide.ucsb.edu/web-standards-checklist/

**Location in New Hierarchy**
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/checklist

I think this page can be a little awkward since the checklist includes both small items ("Include a document title") as well as broad topics ("Ensure media is accessible"), so I could go either way on retaining it. I _do_ think it provides a nice overview of the guide.

Either way, we'll have to migrate this one after everything's in place, so we might be able to better see if it's worth migrating once the other pages are set.

**Comment by rvizena** [comment]
I agree that as-is it might be a little too convoluted, so I feel we should table this page's creation until we get close to launch and find it's place within the new site.

**Comment by rvizena** [comment]
Page has been created and attached to Resources menu. We need to run through each section and refine and fix links, if necessary.
[https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources/checklist](url)

**Comment by tenken** [comment]
* the group is split on keeping this page / checklist. unpublish for now and revisit for later. Maybe an Accessibility checklist on its own.

**Comment by rvizena** [comment]
I added a note on the page and unpublished it.
