### ISSUE TITLE
Migrate "Contact" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#392]
#384 

**Legacy Page**
https://webguide.ucsb.edu/contact/

**Location in New Hierarchy**
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/contact

Not sure if we also want to keep the contact form that's on the new page?

-----------

### Join Mailing List

The UCSB-Web Mailing List provides a forum for UCSB web professionals to exchange
information about web design, development, best practices, and other
web-related topics at UCSB. Web Standards Group meeting and event notices are
also distributed via this list.

To join the UCSB-Web Mailing List, send an email asking to subscribe to the
co-chairs at [wsg-chairs@connect.ucsb.edu](mailto:wsg-chairs@connect.ucsb.edu).

### By E-mail

Email sent to [wsg-chairs@connect.ucsb.edu](mailto:wsg-chairs@connect.ucsb.edu)
will be directed to the current Web Standards Group co-chairs.

### In Person

Attend a meeting of the Web Standards Group, which generally meets the first
Tuesday of every month. Attendance is open to all UCSB IT professionals. Sign up
on the mailing list above for information about attending the meeting.

**Comment by rvizena** [comment]
Hey @loganfranken, I think this is a good start in regards to the copy.  What I'm thinking we can add to this, and I will take care of, is a re-usable Drupal block for Mailing list adds where they can simply provide Name/email/Dep't for joining the mailing list / WSG. 
One thing we would like to add to this is a small bulleted list of Member Benefits.

**Comment by loganfranken** [comment]
Sounds good to me, @rvizena!

**Comment by rvizena** [comment]
- Updated copy moved into the [Contact](https://dev-webguide-ucsb-edu-v01.pantheonsite.io/contact) page.  

- Updated 'Contact WSG' Drupal webform .

- Footer link to Contact page added.

closing
