### ISSUE TITLE
Create 'About Us' subnav with Members pages

### ISSUE THREAD

**Issue by rvizena** [UCSantaBarbara/webguide#396]
## Issue

The **[About WSG](https://dev-webguide-ucsb-edu-v01.pantheonsite.io/about-wsg)** section of the site has the opportunity to utilize a 3rd level navigation and support several pages that make up the large amount of content.

* Should more of these pages be consolidated or does the 3rd level navigation seem appropriate with these sub-pages?

The following pages have been created along with the Navigation System and Submenu Header:
/about-wsg **Landing page**
/about-wsg/history **History of WSG page**
/about-wsg/meet-the-group **Current Members List**
/about-wsg/members-access **Members Only login**

**Comment by rvizena** [comment]
Reviewed at WSG meeting 9/1/20. 

- [Landing page](https://dev-webguide-ucsb-edu-v01.pantheonsite.io/about-wsg) will consume some Panopoly video content, as discussed (Ryan) 

- Approvals to move forward with authentication access on [Login page](https://dev-webguide-ucsb-edu-v01.pantheonsite.io/about-wsg/members-access) (in a new issue). 

- Populate 'Current Members' list based upon last 12 months of activity (Ryan)

**Comment by tenken** [comment]
* the Current Members list which pulls data from the Google Sheet attendance list periodically has been completed. It may be seen at: https://dev-webguide-ucsb-edu-v01.pantheonsite.io/about-wsg/meet-wsg-group

**Comment by tenken** [comment]
* member info pages done.
