### ISSUE TITLE
Embed Dynamic Analytics

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#4]
Dynamic, real-time analytics should be embedded on the "Browsers" page (http://www.ucsb.edu/webguide/browsers) rather than static images.

Alternatively, we could remove the analytics and replace them with a simple statement that those managing UCSB websites should monitor their own analytics.

**Comment by loganfranken** [comment]
URL of the page in the GitHub-hosted repo:
http://ucsb-wsg.github.io/browsers/

**Comment by UCEAP-JCOLON** [comment]
If we could get information to populate from a source that would be ideal. Browser stats that become stagnate would be dated and misinformative quickly. If we can keep current from auto-populating a source that would be ideal.. Otherwise I would opt to remove..

**Comment by tenken** [comment]
I will be submitting an email request to ETS and IA regarding 4 piwik embed graphs. I will be including this small temporarily available demo page as an example:
http://demo02.id.ucsb.edu/

**Comment by tenken** [comment]
Approval was granted by Public Affairs to include the embedded Piwik info. A request was sent to ETS for the embed code. Waiting feedback from ETS.

**Comment by loganfranken** [comment]
Hey @tenken! Did ETS ever get back to you about this? Anything I could help with?

**Comment by tenken** [comment]
Yes, they asked that someone goto their office and perform the task by hand there. And to setup a meeting via email or CorpTime. i replied to the ETS ticket -- which I guess was the wrong thing to do. I will try to follow up with them via email or soemthing.

**Comment by loganfranken** [comment]
If this is difficult to accomplish, I would like to again suggest that we remove the analytics altogether and ask that those maintaining websites gather analytics data for their own websites.

Although I think it's helpful to get a general sense of which browsers/platforms to support, there's also a danger that people could assume their website's traffic matches that of the ucsb.edu website, which likely isn't true.

**Comment by loganfranken** [comment]
Could we tag this issue for discussion tomorrow?

**Comment by loganfranken** [comment]
The group decided to rework this page to (1) remove the analytics and (2) emphasize that maintainers of a website need to gather statistics for their own users.
