### ISSUE TITLE
Create a "Discuss at WSG Meeting" Label

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#40]
Hey, how would all feel about having a "Discuss at WSG Meeting" (or something similar) label for GitHub issues so we can easily spot what needs to be discussed at a monthly meeting?

**Comment by UCEAP-JCOLON** [comment]
Sounds like a good idea!

**Comment by tenken** [comment]
I have created a label "Item for WSG Meeting" which can be applied to Issues.

We already have a Discussion label and I want to differeniate between the two.
- discussions are simply online thoughts, concerns or inquiries.
- item for wsg meeting is something in the issue queue that should be addressed in the next meeting.

I believe you probably want to make the label less formal than a bonified agenda item, but I hope that "items" in the issue queue can be added to the agenda formally as needed prior to a meeting if possible.

This new label is to help identify issues quickly when co-chairs visit Github during a meeting.

**Comment by fablio-work** [comment]
Awesome!!

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by loganfranken** [comment]
Thanks @tenken! This all sounds perfect to me; I think we're good to close this issue.
