### ISSUE TITLE
Migrate "Examples" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#404]
#384 

**Legacy Page**
https://webguide.ucsb.edu/examples/

**Location in New Hierarchy**
???

Given the new campus branding, I'm not sure if we want to change the examples to reflect the websites that adhere to the new branding?

-----------

The following websites are examples of **high-traffic, high-profile** websites
that adhere to the best practices outlined in the Web Standards Guide:

### Campus-wide Services

* [Admissions](https://admissions.sa.ucsb.edu/)
* [Office of the Registrar](https://registrar.sa.ucsb.edu/)
* [Library](http://www.library.ucsb.edu/)
* [Division of Student Affairs](https://www.sa.ucsb.edu/)
* [Graduate Division](https://www.graddiv.ucsb.edu/)

### Major Academic Units

* [College of Engineering](https://engineering.ucsb.edu/)
* [College of Letters and Science](http://www.ltsc.ucsb.edu/)
* [College of Creative Studies](https://ccs.ucsb.edu/)

**Comment by loganfranken** [comment]
Added this here:
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/examples

**Comment by ericmayes** [comment]
As far as our SA Sites, Admissions and Division of Student Affairs have been updated, Grad Div is launching early next year. Registrar hasn't migrated to the web theme so we may want to remove that and Grad Div until they are updated. One idea I have is that this list could be Core sites only (what UCOP calls our core sites). So any Core site that has the webtheme and meets a certain Siteimprove score (possibly 85). Core sites are Bookstore, Disabled Students, Extension, Grad Div, HR, Library, UCSB Home, Office of Development, Student Health, Student Housing, Summer Sessions, and Undergrad Admissions. So of those, UCSB Home, Admissions, DSP, and Office of Development are up to date (using web theme and acceptable siteimprove score) with Student Health and Grad Div launching early next year. 

But this list was also based on some analytics we had, so we may want to figure out any other high traffic sites we want to add. I would have to check Recreation, but they have the new branding and most likely high traffic. When Student Health is updated it will be a good example. They have very high traffic over `140k users for the year. We would need units around campus to give us their highest traffic sites by user if possible. Seems like we just need a small solid list of examples though here, but maybe it could be a goal for units to be recognized on this list.

**Comment by tenken** [comment]
I like the list as-is. Wrt Eric's comments I'm ok limiting the sites to "Core" examples but if we do that I suggest the page explicitly say that a list is our "Core" sites and with a minimum Accessibility score (I don't think there's a need to omit these details). Otherwise I propose we close this ticket with an eye towards launching the site and eventually editing this page later.

**Comment by rvizena** [comment]
Modified the page styles, added pg to the secondary Navigation menu Resources and added a third block "notables" to the two that are moving over.
[https://dev-webguide-ucsb-edu-v01.pantheonsite.io/resources/examples](url)
