### ISSUE TITLE
Migrate "Site Map" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#409]
#384 

**Legacy Page**
https://webguide.ucsb.edu/site-map/

**Location in New Hierarchy**
???

Do we already have a site map on the new Drupal site?

**Comment by rvizena** [comment]
Yes, we have the sitemap.xml module running.  We just need to configure prior to launch, and then submit to search engines the day of launch. 

closing.

**Comment by loganfranken** [comment]
Hey @rvizena!

sitemap.xml looks good!

Did we want to have a dedicated "Site Map" page as in the past?

**Comment by rvizena** [comment]
hmmm...good question @loganfranken! I'm all for dropping it and including it in, say, our 'Checklist page" or SEO page under 'Content'.  I see there is already a mention of it on the checklist, so I'll include some additional verbiage on the SEO page.  Let me know if you think we should keep it as a page, or if it should appear somewhere else besides SEO.  
thoughts @tenken?

**Comment by rvizena** [comment]
verbiage added to page. No checklist for now, as discussed in meeting.
