### ISSUE TITLE
"TLS Everywhere" Recommendation

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#41]
Related to #39:

(Thanks for bringing this up, @garster!)

I'm wondering if we should include something in the guide about the growing [SSL/TLS Everywhere movement](https://letsencrypt.org/2014/11/18/announcing-lets-encrypt.html)?

This is now reaching a fever pitch with the recent federal mandate: [HTTPS-Everywhere for Government announcement](https://www.whitehouse.gov/blog/2015/06/08/https-everywhere-government).

In the past, the idea was that you should only provide HTTPS connections where the user is providing secure information (login screens, etc.). The argument (as I always understood it) was that the latency and administrative overhead associated with HTTPS was not worth it unless you had security concerns.

With the growing number of HTTPS-only websites (like GitHub here), though, the web is slowly turning the tide towards HTTPS in most places, which has led to the natural conclusion: why not just have it everywhere?

I'm wondering if we should address this within the guide?

(I know very little about this area, so _definitely_ feel free to jump in and correct my terminology/understanding.)

**Comment by tenken** [comment]
My understanding is the slow adoption (in the last years) for HTTPS everywhere was:
- on older servers, and shared-hosting, things like high strength SSL encryption and (non-cached) DNS lookups slowed down servers for all clients. Eg, the simpler the configuration setup the more workload a server could handle. On recent hardware I believe this argument to be largely unfounded (unless you talk about shared hosting plans).
- depending on your SSL and server configuration (single cert, wildcard cert, san cert -- single app server vs shared-hosting server). There is administrative maintenance keeping certificates up to date. Newer technologies such as SNI and the recently usable campus-wide (eg, 2-3 years?) SAN certificates again make this overhead much less than it used to be.

Offhand, regardless of whether we address this within the guide the internet will move forward with a standard. If anything we may want to link the announcement above and simply say "we advocate using SSL on all websites if possible." Such a notice could become superfluous in the future.

**Comment by fablio-work** [comment]
I just put a comment up on the github ticket with a bit of additional info.

I lean more towards a presentation of the information and letting the reader decide.

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by tenken** [comment]
As an additional datapoint, Github Pages currently does not support SSL through their CDN, see:
https://github.com/isaacs/github/issues/156

**Comment by loganfranken** [comment]
This ticket was specifically about whether or not we should recommend HTTPS-only on the Guide; did we decide we didn't want to do that?

**Comment by tenken** [comment]
Github Pages doesnt support SSL within the Guide, so I'm not sure what we're approving or not approving :D

I dont mind fielding a new question when the technology stack supports it. :)

I was also just happy to get under 10 open issues by closing it

**Comment by loganfranken** [comment]
I added a wiki page with this suggestion in hopes we can work it into the guide at some point in the future:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/SSL-TLS-Everywhere
