### ISSUE TITLE
Migrate "UCSB Graphic Identity" Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#410]
#384 

**Legacy Page**
https://webguide.ucsb.edu/ucsb-graphic-identity/

**Location in New Hierarchy**
???

This page just redirects over to the Public Affairs website. Not sure if we want to bring it over or not?

-----------

Historically speaking, this webguide provided recommendations on graphics identity for UCSB affiliated websites. In November 2015, the department of Public Affairs and Communications released a toolkit regarding UCSB Graphics Identity. This new material, which is itself a living document, effectively replaces any prior recommendations the Web Standards Group put forth regarding websites developed for/by the campus.

The toolkit provided by Public Affairs and Communications may be found at the [UC Santa Barbara Graphics Identity Website](http://www.ucsb.edu/graphic-identity/).

**Comment by rvizena** [comment]
Graphic Identity page is now under the 'Design' section of the new site at:
https://dev-webguide-ucsb-edu-v01.pantheonsite.io/design/uc-santa-barbara-branding
