### ISSUE TITLE
Feedback on subdomain for ucsb.edu webguide

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#45]
On June 01, 2015 the WSG received permission from UCSB NOC to place the WSG webguide within a newly created subdomain of ucsb.edu

In my communications outlining the request to the UCSB Hostmaster I requested:

> The ucsb web standards group would like to request that the existing UCSB webguide URL at:
> http://www.ucsb.edu/webguide/
> Be given a 3rd level domain name such as webguide.ucsb.edu whose content is hosted via Github.

I am opening up a small discussion to those WSG attendees that are using Github currently to offer feedback on what they think the domain name should be. Is everyone ok with a name such as webguide.ucsb.edu ?

The approval message read (redacting minor details):

> While this is quite unusual in that it does not adhere to the org chart
> there's no doubt you've been working -- with James, of course -- to
> create a valuable community around web development and associated best
> practices, so we'll make this happen.  This request is approved; please
> continue to coordinate with hostmaste regarding appropriate DNS configuration.

Is "webguide" a clear enough name? Is there perhaps something more concrete we can use as the site name. If I google webguide I guess I feel it's a little unclear what kind of site this is:
http://lmgtfy.com/?q=webguide

For example Stanford has Identity.stanford.edu and related subpages:
https://identity.stanford.edu/web-toolkit/

Thoughts? Feedback? Both are appreciated! I'll be sending an email next week on DNS and subdomain name choice. I dont want to raise this at a meeting as an order of expediancy and not have it get lost or buried by NOC.

**Comment by loganfranken** [comment]
I personally like "webguide": "Web Standards Guide" and the shortened, "Web Guide," have been familiar, long-standing terms used on campus (IMO).

I think it also has a slight technical bent, which I think is important for the future for the Web Guide: Public Affairs is better equipped to deal with issues of "Identity" and "Brand," whereas we're better equipped to advise on technical matters.

**Comment by UCEAP-JCOLON** [comment]
I too like webguide.ucsb.edu

**Comment by garster** [comment]
I think webguide.ucsb.edu is the right choice. I think it is generic enough and specific enough.

**Comment by tenken** [comment]
All right, I'm going to call this a consesus around _webguide.ucsb.edu_ and will be requesting that subdomain. I'll be configuring the repositories to work with that _CNAME_. So for now I will lock this issue  until either technical difficulties block this subdomain request from occuring, or the matter is resolved as a working webguide.ucsb.edu subdomain.

**Comment by tenken** [comment]
On June 17, 2015 the UCSB Hostmaster made webguide.ucsb.edu and www.webguide.ucsb.edu live to the public.

Now we just need to deal with redirecting the old site traffic to the new URL.
