### ISSUE TITLE
Simplify Automated Build Steps

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#48]
As discussed in #46, I would like to find a way to integrate the `jekyll serve` and `jekyll watch` commands into a single call to `gulp`

**Comment by tenken** [comment]
This will likely have to assure the sitemaps gem is included in gemfile as well (or perhaps it wont matter for Gulp persay).

I'm just saying local work probably needs to be aware of the sitemaps gem dependency -- but I just added the config change online without integrating the solution into a local build/test repository structure. :D

**Comment by loganfranken** [comment]
And just to assuage any concern: the sitemaps gem didn't give me any trouble.

Thanks @tenken!
