### ISSUE TITLE
Revise Web Analytics recommendation in webguide for campus divisions

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#49]
The campus Policy department sent out revised guidelines on click through agreement usage on campus. On page 3 of the PDF they outline Google Analytics acceptance/usage on campus:
http://www.policy.ucsb.edu/policies/advisory-docs/clickthrough-guide.pdf

We should revise the webguide guidelines to clarify this change in policy.

**Comment by ilessing** [comment]
The part about Google Analytics:

> UCSB REQUIREMENTS RELATING TO THE USE OF WEB ANALYSIS TOOLS
> All web pages that use third-party (non-UC) web analysis tools, such as Google Analytics, must link to:
> UCSB's "University of California, Santa Barbara Privacy Notification Statement" web page at: 
>     http://www.policy.ucsb.edu/privacy-notification/.
> Google Analytics (GA) account administrators must configure GA not to share GA data, so that the usage statistics will only be available for UCSB's local use. (Account admins: for each GA account, check “Do not share my Google Analytics data" on the "Edit Account and Data Sharing Settings” screen.)

To me that says we CAN use Google Analytics on our sites now as long as we link to the privacy policy and don't widely share the usage stats.

Is that what the rest of you understand?

**Comment by UCEAP-JCOLON** [comment]
That is how I interpret it as well!

**Comment by garster** [comment]
It tells me we can use Google Analytic, if we promise to set some settings and do some links.

**Comment by loganfranken** [comment]
Given your edit, this can be closed, right @tenken?

**Comment by tenken** [comment]
Ya, I think so I was just waiting for feedback. but I guess people could always comment on a closed issue? I guess I'm saying I (personally) like leaving issues open for like 3 days or so after any changes/work done in case there are comments ...

**Comment by ilessing** [comment]
google seems to have changed the language in their settings page from what is mentioned in the policy.  Gone is the _Do not share my GA data_  Instead there are a series of checkboxes that I just left un-checked. 
![googleanalyticssharingsettingsscreen-shot-2015-06-29](https://cloud.githubusercontent.com/assets/275899/8420709/936016e4-1e7a-11e5-9578-11d93adfea8c.png)
