### ISSUE TITLE
Search Results link to old webguide subdirectory, not custom domain.

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#51]
The search results appear to link to the old subdirectory for the webguide and not the new webguide.ucsb.edu domain. This bug should be addressed.

**Comment by tenken** [comment]
Hey, @loganfranken , does the site.baseurl and the Google Custom Search at https://github.com/ucsb-wsg/ucsb-wsg.github.io/blob/master/scripts/main.js#L92 need to be updated for the new webguide.ucsb.edu url?

**Comment by loganfranken** [comment]
Hey @tenken! Good catch!

Yeah, as far as I remember, Mihoko set up the custom search engine originally. She may be able to change it?

If not, we could always create a new one.

**Comment by tenken** [comment]
Ah yes, I recall now the old webguide was integrated with Google Custom Search (GCS) that powers also the www.ucsb.edu search. Eg, searching the campus will return webguide results from the legacy webguide URL. I also recall IA saying they could include a new subdomain such as webguide.ucsb.edu if it gets made and we notify them. I'll see if they can update the GCS to include the new domain.

Baring, that possibility I'm sure we could roll our own.

**Comment by tenken** [comment]
Email request sent to IA.

**Comment by tenken** [comment]
All those slashes in the directory names for site content ... are probably not a good thing ...
http://webguide.ucsb.edu/sitemap.xml

**Comment by tenken** [comment]
@loganfranken can you update the google custom search used on the site to use the new subdomain?

**Comment by loganfranken** [comment]
Hey @tenken!

Sorry, I'm confused: as far as I know, I don't administer the Google Custom Search used on the Web Guide so I can't update it. Did you hear otherwise?

If we want to just move forward with creating a new Google Custom Search catered to the new subdomain, I can totally do that.

**Comment by loganfranken** [comment]
Augh, sorry, you were totally right: I do administer this one.

Updated!

Looks like results are now pointing to the new subdomain, so I think we can close this whenever.

(Sorry again for the confusion)

**Comment by tenken** [comment]
Thanks for the effort! No worries :)
