### ISSUE TITLE
HTML5 Header Hierarchy Recommendations

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#54]
In addressing HTML5 validation issues with the current templates (see: https://validator.w3.org/nu/?doc=http%3A%2F%2Fwebguide.ucsb.edu%2Ftemplates%2F), I noticed that our current templates use the HTML5 recommendation of using a `h1` element per sectioning element.

(In other words, `nav` gets a `h1`, each `section` gets a `h1` and so on)

Even though this is a HTML5 recommendation, it doesn't always play well with screen readers and other assistive technologies (which have traditionally expected a single `h1` on a page).

We should do some research and (1) make a recommendation and (2) update the best practice templates.

**Comment by ericmayes** [comment]
I believe the multiple approach is ok in some cases, but it can still lead to confusion for a screen reader user:

Screen reader users typically like to quickly navigate to the first h1 in a document with the 1 key to determine the title of the page. And I believe not all screen readers actually read the HTML title tag! Screen reader users can then navigate the h2s with the 2 key to determine the major page sections and sub-sections. They can also open a list of all headings to navigate by level. 

If h1s are used to begin each sub section it might become a bit more difficult to differentiate document and different levels of section headings. It would also be difficult to quickly jump back to the title and beginning of the main content. 

Navigating by ARIA landmark does solve some of these issues, but I don't think there isn't any reason a page couldn't be structured with one main H1 per page. It still seems like the safer, less confusing approach for everyone. Only place I see it being beneficial for multiple H1s are inside of  <article>s etc. I don't see a good reason to have to use H1 within navigation headings or within the footer really but that's just my opinion.

Also, I think multiple h1 could also hurt SEO rankings by giving importance to multiple heading levels (unless of course these only relate to h1's inside of the header area/landmark now)

All that being said. if the h1s are inside of < section >, < article >, or < aside > they get announced as if they are H2 within a screen reader, and they are perfectly fine! We might have to test this, but I know it works on some screen readers like Jaws.  I also think this type of use wouldn't negatively impact SEO either but I could be wrong. We should set up a test with each type of HTML 5 section

**Comment by loganfranken** [comment]
Thanks for all of the info, @ericmayes!

It looks like we need to test for the following:
- Can screen readers correctly read multiple `h1` tags?
- Can a screen reader user quickly navigate by heading in the presence of multiple `h1` tags?
- Do multiple `h1` tags negatively impact SEO?

For my reference, here are the HTML5 "sectioning" elements that allow for a new header hierarchy according to the [HTML5 spec](http://www.w3.org/TR/html5/dom.html#sectioning-content-0):
- `article`
- `aside`
- `nav`
- `section`

**Comment by loganfranken** [comment]
A note on multiple `h1`s and SEO (as far as Google goes):
https://www.youtube.com/watch?v=GIn5qJKU8VM&feature=youtu.be

(Basically: you're fine to use them, as long as you use them properly)

**Comment by loganfranken** [comment]
And some articles on the accessibility side of things:
- https://www.paciellogroup.com/blog/2013/10/html5-document-outline/
- http://juicystudio.com/article/html5-outline-algorithm-jaws.php

**Comment by loganfranken** [comment]
Alright, I created some tests:
http://loganfranken.github.io/web-standards-testing/html5-header-hierarchy/index.html

Basically, there are three different types of documents; the [standard header hierarchy](http://loganfranken.github.io/web-standards-testing/html5-header-hierarchy/standard-hierarchy.html):

``` html
  <h1>Page Title</h1>

  <h2>Navigation Header</h2>

  <h2>Article Header</h2>

  <h3>Section Within Article Header</h3>

  <h3>Article Subheading</h3>

  <h2>Aside Header</h2>
```

The [HTML5 hierarchy](http://loganfranken.github.io/web-standards-testing/html5-header-hierarchy/html5-hierarchy.html):

``` html
  <h1>Page Title</h1>

  <nav>
    <h1>Navigation Header</h1>
  </nav>

  <article>
    <h1>Article Header</h1>

    <section>
      <h1>Section Within Article Header</h1>
    </section>

    <h2>Article Subheading</h2>
  </article>

  <aside>
    <h1>Aside Header</h1>
  </aside>
```

And the [HTML5 elements with standard hierarchy](http://loganfranken.github.io/web-standards-testing/html5-header-hierarchy/html5-standard-hierarchy.html):

``` html
  <h1>Page Title</h1>

  <nav>
    <h2>Navigation Header</h2>
  </nav>

  <article>
    <h2>Article Header</h2>

    <section>
      <h3>Section Within Article Header</h3>
    </section>

    <h3>Article Subheading</h3>
  </article>

  <aside>
    <h2>Aside Header</h2>
  </aside>
```

According to the [HTML5 Outliner](https://gsnedders.html5.org/outliner/), these should all produce the same document outline:

![image](https://cloud.githubusercontent.com/assets/1024444/10520801/1ba6e370-7321-11e5-9660-29119f278a32.png)

**Comment by loganfranken** [comment]
I was only able to run tests in NVDA, but the results are enough to act on:
http://loganfranken.github.io/web-standards-testing/html5-header-hierarchy/results.html

Basically (as @ericmayes predicted), using the HTML5 approach to headings is a bad idea for screen readers: NVDA doesn't change how it reads the headers based on where they are situated within the document outline and the heading navigation by number keys breaks down (you have to navigate the HTML5 example by just pressing `1` over and over).

So, with that, I think we should (1) write a recommendation to use the standard approach to heading hierarchies (even _with_ HTML5 elements) and (2) fix the use of multiple `h1`s within the guide itself.

**Comment by loganfranken** [comment]
Added a recommendation within the wiki:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Accessibility-Tips

**Comment by loganfranken** [comment]
Just wanted to follow up: let me know if I should split up the PR against the best practice templates or if it's good to go as-is. Thanks!

**Comment by loganfranken** [comment]
A new article came out basically saying we should stop trying to make the HTML5 document outline happen:
http://html5doctor.com/computer-says-no-to-html5-document-outline/

Updated the wiki to reflect that:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Accessibility-Tips#nest-headings-properly
