### ISSUE TITLE
Add recommendation for Read More Links

### ISSUE THREAD

**Issue by ericmayes** [UCSantaBarbara/webguide#56]
One interesting tip I came across lately for accessible "read more" links. Read More links are known to be very meaningless to screen reader users, unless you combine them with aria-labelledby in the link and multiple ID's as shown below. This might be a nice recommendation for the guide. Thoughts?

``` html
Accessible Read more links
<h1 id="articleHeading1">Article Heading</h1>
<p>Some article content. 
<a href="articles.html" id="articleLink1" 
   aria-labelledby="articleHeading1 articleLink1">
   Read more
</a></p>
```

**Comment by loganfranken** [comment]
Interesting! Thanks for sharing, @ericmayes; I didn't realize this was such an issue.

Looks like there's a good discussion about this on the a11yproject.com's GitHub:
https://github.com/a11yproject/a11yproject.com/issues/269

More specifically, that discussion leads to an example similar to the one you posted:
http://codepen.io/grayghostvisuals/pen/Gtoua

I'm down for putting this into the GitHub wiki and then eventually integrating into a rewrite of the accessibility portion of the web guide.

**Comment by loganfranken** [comment]
Alright, I added this to the wiki:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Accessibility-Tips#ensure-read-more-links-are-accessible

I think we can close this issue for now, unless anyone has anything they want to add/change?

**Comment by loganfranken** [comment]
Good morning @ericmayes @tenken @cfwebmaster!

I think we're clear to close this one? Unless anyone disagrees?

**Comment by UCSB-jcolo** [comment]
I think its looking good.
Way to go guys.

**Comment by loganfranken** [comment]
@cfwebmaster Are we good to close this one?
