### ISSUE TITLE
Favicon and Touch Icons

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#58]
This page's (http://webguide.ucsb.edu/favicon-and-touch-icons/) content seems outdated. 

Looking at a tools like http://www.favicon-generator.org/ and http://realfavicongenerator.net/ they generate HTML code to place in pages to reference different files.

I would suggest someone do some research into this and see if the code below is correct, then update the page.

```
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
```

**Comment by loganfranken** [comment]
Yes! Another page that badly needs updating; thanks @garster!

**Comment by tenken** [comment]
What would we want to include in a favicon/touch icon recommendation?

I typically use this on a site ...
https://www.drupal.org/project/responsive_favicons

But to better enlighten myself I did a quick google for "favicon 2015" and found this blog post:
https://realfavicongenerator.net/blog/favicon-why-youre-doing-it-wrong/

Which ultimately linked to this repository which has existed for 2 years and was updated 12 days ago. 
https://github.com/audreyr/favicon-cheat-sheet

Is it possible to take excerpts from this favicon cheatsheet and possibly link it into the webguide as a living-document resource ...

I'm not sure of the best approach here. Eg, the favicon cheatsheet seems to me to be:
1. comprehensive
2. kept up to date

If we take all this content and include it into the webgudie, we'd have to be moderating it constantly for updates (which I guess is doable by future contributions) ...

**Comment by loganfranken** [comment]
Basically, I think we should include a terse description of what icons you should create/include to get people up and running quickly.

I'm totally not adverse to just linking to the favicon cheat sheet although (1) there was pushback during the original rewrite about including links to external websites and (2) the cheat sheet is a _bit_ overwhelming (at least to me) at first and doesn't necessarily provide a quick reference.

So I would still vote for maybe providing a simplified checklist for our readers (although I agree it's a maintenance pain), but I would totally support linking to an external resource if the group supports that plan.

**Comment by loganfranken** [comment]
I took a shot at this (#80), basically just writing a few sentences that explain the _bare minimum_ required (followed by a link to the [cheat sheet](https://github.com/audreyr/favicon-cheat-sheet) @tenken provided).

If we go with this rewrite, I think it could be helpful to create a set of favicons for that cover _all_ of the use cases specified by the [cheat sheet](https://github.com/audreyr/favicon-cheat-sheet) and then provide these for use by the website maintainers; then we could come back and update this page to say, "hey, but if you _wanted_ to support all platforms, here's a set of images to get you headed on your way."

**Comment by tenken** [comment]
We reviewed this item at the December 01, 2015 meeting. The page looks fine as is for an update. We discussed having Public Affairs provide a set of example favicon files in a .zip file as examples for websites. We could then add to this page of documentation that the Graphics Identity package includes such an example.

**Comment by loganfranken** [comment]
Hey @tenken: are we good to go to merge #80?
