### ISSUE TITLE
Freshen Viewport Dimensions content

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#59]
Best practices change quickly. I feel that the content on http://webguide.ucsb.edu/viewport-dimensions/ has some issues, and does not reflect the current trends in web design.
- Mobile devices are quickly becoming the majority and should become the primary focus.
- Why are we recommending targeting "display adapters" (antiquated and confusing term) of a certain sizes. It should look good on all sizes.  I agree about looking towards a maximum width such as 1024 pixels as there is not really anything smaller then that today. I just think the wording could be improved.
- A "mobile" site actually does more harm than good nowadays. The info under the Mobile devices section should be entirely re-written to push readers toward a responsive design. I know the MWF was a big deal, but now it is just an outdated idea (3 years, yes things move quickly) and references should be removed.  
- Responsive Layouts section can be expanded a bit.
- Printable alternatives also seems antiquated, but yes I still have a printer and find a hard copy of info is sometimes good to have with me. Maybe expand to suggest the print css query, Also explain that print views need to be flexible since it will print differently depending on the OS and print driver.

**Comment by loganfranken** [comment]
I agree with @garster on all points! Thanks for bringing this up!

**Comment by loganfranken** [comment]
Anything you wanted to add/change to the rewrite, @garster? Or did I tackle everything?

**Comment by tenken** [comment]
Added tag so that we can review next meeting for additional feedback if necessary (and as an overview of progress).

**Comment by loganfranken** [comment]
Awesome! Thanks @tenken!

**Comment by tenken** [comment]
We reviewed this issue on December 01, 2015 for the group. Logan added that now RWD is the defacto approach to designing websites on campus.
