### ISSUE TITLE
Investigate analytics options for webguide

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#62]
The webguide has been at github for a while now. So far as I can tell the Traffics tab under [Graphs](https://github.com/ucsb-wsg/ucsb-wsg.github.io/graphs) isn't capturing Google Analytics like data ... and I'm not sure why. I was under the impression that it should be capturing visitor traffic (i imagine ucsb.edu should show up _somewhere_ on the traffic page):

https://github.com/blog/1672-introducing-github-traffic-analytics

I for one would like to know what content people browsing the site (not the repo) are finding useful. It would better allow us to focus on content updates users want. Since Github Pages does not allow for custom javascript directly there are a few options available to us, easiest may be this GA Beacon service:

https://github.com/igrigorik/ga-beacon

This is just food for thought, and if nobody has any input on this it's ok with me if this goes nowhere.

**Comment by loganfranken** [comment]
Yeah, I think that tab is strictly the traffic going to the repository itself (not the website).

I might be missing something: is there a reason we can't just stick a Google Analytics script into the bottom of the template?

**Comment by tenken** [comment]
I dunno, I was reading online that google didnt allow custom javascript or something to run on github pages .... https://news.ycombinator.com/item?id=7016440 ... oh wait, maybe they're talking about Repository traffic (sighhh). :P

Maybe this would work?
http://stackoverflow.com/a/17209831/1491507

**Comment by loganfranken** [comment]
@tenken @UCEAP-JCOLON I think it makes sense for you to be given access to the Google Analytics and then you both can revoke my access. What Google account e-mail can I use for both of you?

**Comment by UCEAP-JCOLON** [comment]
californiaimage@gmail.com

**Comment by UCEAP-JCOLON** [comment]
Thanks Logan
