### ISSUE TITLE
Move IT Resources to GitHub

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#68]
I'm wondering if we should move the IT Resources content to GitHub (possibly the wiki) so it can be closer to where the actual guide development is occurring?

At the very least, we could probably create issues for the "Future Areas of Development" and start working on completing those.

**Comment by loganfranken** [comment]
Sorry, forgot to post the pages:
- https://it.ucsb.edu/resources/web-standards-guide-resources
- https://it.ucsb.edu/resources/web-standards-guide-resources-email-addresses
- https://it.ucsb.edu/resources/web-standards-guide-resources-markup-and-styling
- https://it.ucsb.edu/resources/web-standards-guide-development
- https://it.ucsb.edu/resources/website-tools

**Comment by loganfranken** [comment]
For reference, the "Future Areas of Development" list (from https://it.ucsb.edu/resources/web-standards-guide-resources):

**Ready to Begin Implementation**
- ~~Missing Copyright Year in Footer (#69)~~
- Best Practice Example favicons (#58)
- How to Use Headers (H1 - H6) (#68)
- How to Use Copyrighted Images
- SEO Standards
- Media query recommendations
- Form design
- ARIA
- Embedding HTML5 video
- HTML5 picture element

**Need Discussion**
- JavaScript Standards
- UX (Usability and User Experience) Standards
- Marketing Standards
- PHP Standards
- XML Standards
- Cloud Hosting/Storage Recommendations
- Google Analytics Standards and Resources
- Source Control Standards and Resources
- Razor Syntax Standards
- HTML5 (and HTML5 markup skeleton)

**Comment by tenken** [comment]
I'm up for moving the content into the Wiki here. I'm not 100% all that isn't there in part because it was supposed to be locked down from the public (loosely).

**Comment by loganfranken** [comment]
Moved "Future Areas of Development" section.

From:
https://it.ucsb.edu/resources/web-standards-guide-resources

To:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Future-Areas-of-Development

**Comment by loganfranken** [comment]
Moved "E-mail Addresses" section.

From:
https://it.ucsb.edu/resources/web-standards-guide-resources-email-addresses

To:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/E-mail-Addresses

**Comment by loganfranken** [comment]
Moved "Markup and Styling" section.

From:
https://it.ucsb.edu/resources/web-standards-guide-resources-markup-and-styling

To:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Markup-and-Styling

**Comment by loganfranken** [comment]
No need to move "Web Standards Guide Development" as it's not relevant any longer:
https://it.ucsb.edu/resources/web-standards-guide-development

**Comment by loganfranken** [comment]
Moved "WSG and GitHub Usage" section.

From:
https://it.ucsb.edu/resources/wsg-and-github-usage

To:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/WSG-and-GitHub-Usage

**Comment by tenken** [comment]
awesome logan. So should we nuke the it.ucsb.edu relevant page(s) so as to not confuse attendees and co-chairs?

**Comment by loganfranken** [comment]
Moved "Tools" section.

From:
https://it.ucsb.edu/resources/website-tools

To:
https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Website-Tools

**Comment by loganfranken** [comment]
Alright, that should be all of the pages.

Hey @tenken: yeah, I would be happy to, but I was concerned with removing a group resource before asking the group. Should we discuss this in an upcoming meeting first?

**Comment by tenken** [comment]
added tag for meeting.

**Comment by loganfranken** [comment]
I went through and tagged each of the IT resources page with a link to the corresponding GitHub page.

I'm slightly uncomfortable actually deleting pages myself, so I'll leave that decision/task up to a co-chair.

**Comment by tenken** [comment]
Oh cute. we cannot "unpublish" items on it.ucsb.edu :/ hmmm ... so I guess we will need to really delete the items ... i will do this later this week. Curious, did you mark all pages herein ?

https://it.ucsb.edu/resources/all

**Comment by tenken** [comment]
I mean I can see pages you've marked with the pink text at the top ... i'm just trying to find a listing of the pages you've edited recently to make the task easier.

**Comment by fablio-work** [comment]
Hi All,
  I have not been following this thread closely and I haven’t looked to see exactly what has been moved over, but
I had a couple red flags go off when I read the recent emails on this:
- not all the resource pages on it.ucsb.edu http://it.ucsb.edu/ are “WSG” pages.  So it doesn’t “feel” to me like we should be trying to move ALL those resource pages.
- possible access control on some of those pages.  I think some(many?) of those pages were not meant for public consumption.  ie: things that the WSG didn’t feel was necessarily appropriate to put in the guide (product recommendations, references to third party organizations) sometimes found a home on a resource page.
  *\* how does the restrictions/availability of access to the github pages differ from it.ucsb.edu http://it.ucsb.edu/?  I think that anyone with a UCSBnetID can access the content on it.ucsb.edu http://it.ucsb.edu/.  Do they need to sign up for a github account to access the new pages?  If so, thats a barrier to participation (for some).  If not, then item two may come into play.

I apologize if I completely "missed the boat" here :-)     Cheers      Aaron

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by loganfranken** [comment]
Hey @fablio-work!

Thanks for your feedback!

We're not planning on moving _every_ it.ucsb.edu page, just the ones that were WSG-related (the ones listed above).

I was concerned about the access restriction as well, but I didn't see anything that couldn't be shared with the public.

The GitHub pages will be open to everyone! (No need for a GitHub account)

**Comment by tenken** [comment]
Ah ok, if its just the ones above then I'll walk thru the list later and delete them after a quick scan of the contents on either end. This answers my previous question.

thanks.

**Comment by fablio-work** [comment]
Cool, thanks Logan!!

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by loganfranken** [comment]
Are we still planning on moving forward w/ removing the legacy IT Resources pages? Or do we want to just keep them up for historical purposes (they all have messages telling users to go to the GitHub wiki instead)?

**Comment by loganfranken** [comment]
Per the meeting today, deleted "Website Tools" from the GitHub wiki, removed the tag on the IT resources page (https://it.ucsb.edu/resources/website-tools) pointing users to GitHub

**Comment by loganfranken** [comment]
I _think_ there was consensus to delete the following IT resources pages:
- https://it.ucsb.edu/resources/web-standards-guide-resources
- https://it.ucsb.edu/resources/web-standards-guide-resources-email-addresses
- https://it.ucsb.edu/resources/web-standards-guide-resources-markup-and-styling
- https://it.ucsb.edu/resources/web-standards-guide-development

Content has been moved to the following wiki pages:
- https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Future-Areas-of-Development
- https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/E-mail-Addresses
- https://github.com/ucsb-wsg/ucsb-wsg.github.io/wiki/Markup-and-Styling

**Comment by garster** [comment]
@loganfranken thank you and I agree. @cfwebmaster and I will review the content on the it.ucsb.edu soon and take action. When that is done we will comment and close this issue.

**Comment by loganfranken** [comment]
Hey there! Let me know if there's anything I can do to help with wrapping this up.

**Comment by garster** [comment]
@cfwebmaster and I were going to meet last Friday for this, but work and other stuff got in the way. Soon.

**Comment by garster** [comment]
This was completed by myself (@garster) and @UCSB-jcolo on 2/19/2016. Closing Issue
