### ISSUE TITLE
Fix Policy Links

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#7]
A good deal of the policy links are broken (http://www.ucsb.edu/webguide/policies).

**Comment by loganfranken** [comment]
URL of the page in the GitHub-hosted repo:
http://ucsb-wsg.github.io/policies/

**Comment by loganfranken** [comment]
I've got a branch going with a fix for most of these, but there are two tricky ones I'm going to research futher:

The **Guidelines for Acknowledgements and Advertising on University Electronic Resources** (http://www.policy.ucsb.edu/policies/policy-docs/advertising-guide.pdf) exists but it's a PDF that never loads (at least for me).

The **UCSB Rules of Conduct** is something that doesn't appear to actually exist: I tracked down a PowerPoint presentation (https://it.ucsb.edu/system/files/Web%20Policies%20Presentation%2011-10%20%28updated%29.ppt) that notes that the Rules of Conduct are _adapted_ from BFB-RMP-8 Exhibit D (http://policy.ucop.edu/doc/7020463/BFB-RMP-8), which we have historically linked to as the actual Rules of Conduct.

**Comment by tenken** [comment]
Thanks for looking into this. I'm at DrupalCon 2015 this week in LA. Let me know if there's anything I can do to help!

**Comment by loganfranken** [comment]
Just got an e-mail back from Tessa Mendez, UCSB's Policy Coordinator:

She fixed the **Guidelines for Acknowledgements and Advertising on University Electronic Resources** (http://www.policy.ucsb.edu/policies/policy-docs/advertising-guide.pdf) link! It's still a little finicky for me in Chrome, but it works consistently in Firefox.

She also confirmed there is no UCSB-speciifc "Rules of Conduct" and suggested the following text:

"This is official University of California, Santa Barbara information. Unauthorized access, disclosure, or use of this information may result in disciplinary action and/or criminal prosecution. See [Rules of Conduct for Rules of Conduct for University Employees Involved with Information Regarding Individuals](http://www.ucop.edu/ethics-compliance-audit-services/_files/compliance/privacy/rules-of-conduct.pdf).”
