### ISSUE TITLE
Update UCSB Web Accessibility Guidelines

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#74]
We need to update the Web Accessibility Guidelines PDF:
http://webguide.ucsb.edu/web-accessibility/

Specifically, I think we need to do two things:
1. Convert the guidelines from a PDF to format that's easier to edit
2. Update the content

I'm not sure if the guidelines are so big that they (1) deserve their own repository or (2) if they could be integrated as a section within the existing guide.

We would need to work with the accessibility/policy heads on campus to make sure we go about it in the right way.

**Comment by fablio-work** [comment]
Wow, Good catch Logan!!  We completely missed that during the 2013 rewrite :-(

I am also a bit confused about the source and purpose of that document.  It looks like 
something the WSG may have created itself in 2006.  The content seems to be almost
a condensed version of the site itself (prior to the 2013 rewrite).  If so, it doesn’t make sense 
to try to recreate it in something other than PDF.  But that brings up the issue of purpose.
If it’s meant to be a condensed, “printable” version of the guide then we might want to handle that 
differently.  It also should maybe not be buried on a page, but be a menu item.

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by loganfranken** [comment]
Oh, I totally see the overlap you're seeing, @fablio-work!

I think this was supposed to be a PDF specific to supporting assistive technology users (rather than a condensed copy of the guide). I think the overlap is just a result of the fact that accessibility guidelines naturally align with web best practices.

Since, as you point out @fablio-work, there is a ton of overlap, we might be able to throw out a lot of this content?

**Comment by fablio-work** [comment]
If the purpose is separate and distinct, then thats a reasonable question.
In addition maybe we should be asking questions like:
- Is there a better source for the info than our site? (possibly not with all the work being done right now)
- Does that distinct purpose warrant repeating sections of the guide?
- If so, can we somehow capture those sections automatically/programmatically?
- can we do so into a PDF?
- does it need to be a PDF?  
- Is there some reason we want/need to provide a cleanly printable version of that subset of content?

I feel like this is one of those lost “corners” of the guide that needs re-evaluating.

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by loganfranken** [comment]
@tenken @cfwebmaster How would you all feel about creating a new repository (e.g. `web-accessibility`) to start fleshing out this content?

I could find a way to convert the PDF to text that we can all edit within that repo.

Alternatively, we could just use the existing wiki here too, but it might be a large enough project to necessitate its own repo.

**Comment by tenken** [comment]
Ya I like that idea. I will try to make it before the meeting for the ucsb-web organization.

**Comment by tenken** [comment]
Created, please see https://github.com/ucsb-wsg/web-accessibility

**Comment by loganfranken** [comment]
Awesome! Thanks @tenken!

**Comment by loganfranken** [comment]
This is now its own project (https://github.com/ucsb-wsg/web-accessibility), so I'm closing this issue.
