### ISSUE TITLE
Remove Protocol-less URL Example From Resources Page

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/webguide#78]
The protocol-less (or protocol-relative) URL is now an anti-pattern:
http://www.paulirish.com/2010/the-protocol-relative-url/

Thus, we should remove it from the "Resources" page:
http://webguide.ucsb.edu/resources/

**Comment by tenken** [comment]
Hmm ... I'm not sure I 100% agree with this suggestion.

Eg, on eap.ucsb.edu we use HTTPS (for student logins). The staff there embed Youtube videos and if they try to use an YT iframe sometimes it was http, othertimes https and depending on the browser version "Mixed Mode" content and browser security policies would items to "disappear" from the page.

Thankfully the Media module for Drupal allows YT videos to be strictly embedded as http, https or protocol-less. As there are dev and production sites for this site, I dont run SSL on my dev site ... so protocol-less for this situation makes sense to me.

In general with regards to a CMS with multiple author(s) of content of varying technical ability -- I think protocol-less is a boon; and a browser feature not being dropped any time soon.

**Comment by loganfranken** [comment]
Hey @tenken: the "Mixed Mode" issues should only occur in a situation where HTTP assets are loaded over HTTPS, not the other way around. So it seems like it simplifies things quite a bit to just have everything requested over HTTPS (if possible)? Or am I missing something?

(This is essentially the same reasoning underlying #39)

**Comment by garster** [comment]
If the file is ran from the local filesystem, than protocol-less URLs will not work. But I don't think even static sites should be developed off of a filesystem, but ran thru a dev webserver for review.

But I think the advantage of using the same protocol as the source page is good, or to use the HTTPS version of external links. 

One day HTTPS is be the default, you will put an TLS cert and redirect everyone to it. Then suddenly all those HTTP links will show an error or just fail to work.

Not to toot my own horn, but I _just_ wrote a bit on this when I was setting up FREE Let's Encrypt Cert on my server http://blog.garyscott.net/2015/11/lets-encrypt-beta-cert-on-nginx/

This is the rant from my post:

> I am a huge “HTTPS Everywhere” proponent. Back in the early 2000s, when I was a webmaster for a bank, they required that anything sent through the website be encrypted. Of course the Online Banking system was fully SSL encrypted, but this requirement was related to the main informational WWW site. The users would browse the site with HTTP, but then the link to Contact Us form went through HTTPS, and after it was switched back to HTTP.
> 
> This was a pain as I had to link to the full url of the HTTPS site. This caused a bit of pain while testing, as you would hop over to the production site from the test site. Anyways long story short, from that moment on I said “Just make it all HTTPS”, redirect all HTTP links to HTTPS for the entire site. I got pushback because it was “slower” but a few years later other major banks starting doing this so I had precedent to make it the way I wanted.

**Comment by loganfranken** [comment]
Toot away! I always love reading colleague's blogs! Thanks for sharing, @garster!

**Comment by garster** [comment]
Well today I got burned with the UCSB Utility Bar sample, when I put it on a HTTPS site. The import to the Google font did not load because it was set to HTTP, and was blocked.

![image](https://cloud.githubusercontent.com/assets/4443025/11480973/643d1de6-974f-11e5-9163-26b9374e0ec0.png)

For me this just keeps pounding the point in on why protocol-less works well or set all external resources to the higher HTTPS.
