### ISSUE TITLE
Approach Public Affairs for Favicon set

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#85]
In issue #58 we discussed updating the favicon recommendations. After review by the group we decided to approach Public Affairs with a request to include a "current" favicon set with the necessary myriad of favicons required for the full example of the favicon cheatsheet we reference.

**Comment by loganfranken** [comment]
Did we end up approaching Public Affairs for a set of favicons?

**Comment by ericmayes** [comment]
We didn't. We have the default favicon but not the set.

**Comment by loganfranken** [comment]
Could we mark this for discussion at the next WSG?

**Comment by garster** [comment]
On http://www.ucsb.edu/graphic-identity/websites it says In need of a favicon for your website? Email web.team@ia.ucsb.edu for the URL to the favicon used on ucsb.edu.

**Comment by loganfranken** [comment]
Just following up: @UCSB-jcolo mentioned that he was going to follow up w/ Public Affairs about this.

Brian Wolf brought up the idea of using SVG for this, but, unfortunately, it looks like support is still pretty light outside Firefox:
http://caniuse.com/link-icon-svg

Ultimately, I think we just need a suitably large (260x260 or greater) PNG file that we can run through a generator (like http://realfavicongenerator.net/).

**Comment by loganfranken** [comment]
Based on the meeting from last week, are one of the co-chairs planning to follow up w/ Public Affairs about getting the favicons?

**Comment by loganfranken** [comment]
@UCSB-jcolo shot me an e-mail with the SVG for the favicon. Here it is:
https://drive.google.com/open?id=0B2rriRQYcoUiTlN1ZHUteTZwUjg

I think we can close this issue since we have the favicon source of truth. We can go through the process of creating and using the favicons in #5.

**Comment by garster** [comment]
I requested this last week and Terry Wimmer sent me this SVG:

[favicon.zip](https://github.com/ucsb-wsg/ucsb-wsg.github.io/files/468292/favicon.zip)

I am not up to speed on all the new variations of favicon we need, so if someone with some knowledge can convert it to what we need that would be great.

**Comment by loganfranken** [comment]
Thanks @garster!

I think this ticket is just to get the favicons from Public Affairs. Unless anyone disagrees, we can close this issue and then focus on making the needed variations of the favicon in #5.

**Comment by loganfranken** [comment]
Hey there! I think we can close this one?
