### ISSUE TITLE
Codify Initial WebGuide Redesign

### ISSUE THREAD

**Issue by tenken** [UCSantaBarbara/webguide#92]
[After todays Jan 05, 2015 WSG meeting](https://it.ucsb.edu/groups/wsg/web-standards-group-meeting-january-5-2016) the group came to the concensus regarding the webguide redesign. This is the tentative workflow:

> The group reviewed the current mockups and voiced opinions on the largeness of the navigation menu and whether it should be at the top of the page, or the left side of the page. Whether the pages should include images or no images.
> Various votes occured this meeting:
> -- Should the menu be the Top of the page or Left side navigation: Top:6 Left:4
> -- Should the pages contain images: Yes:5 No:4
> -- Should the pages show images and have the menu overlay images/text: Yes:6 No:3
> 
> With the above notes the WSG group has collectively decided to move forward with the redesign using the current mockup as a template. Having the top menu "open" on the homepage by default and closed into a hamburger on childpages by default. On child pages the menu should overlay any text/images as needed without pushing content around.
> 
> The tentative timeline/workflow is:
> 1. commence redesign work.
> 2. build bootstrap example of redesigned webguide / pick images per pages
> 3. get approval from group on final
> 
> Eric Mayes will help for redesign with assets from Graphics Identity at UCSB. If images aren't liked on/within the pages then I suggest we display:none the images in mockups to see how they appear at the top of the page.
> 
> After the above work is done this template should be an example/basis for the best practices example.

**Comment by garster** [comment]
I am closing this issue since it was launched. Thanks everyone.
