### ISSUE TITLE
Links to Mailing list is broken

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#95]
On several pages there is a link to join the WSG mailing list. 
- http://webguide.ucsb.edu/contact/
- http://webguide.ucsb.edu/about/
- Maybe more

This links (https://lists.ucsb.edu/mailman/listinfo/ucsb-web) get redirected to basically a blank page wiht tabs that do not work (https://lists.connect.ucsb.edu/ucsb/)

Does anyone have any insight into why this happened. It seems all https://lists.ucsb.edu/ urls are being redirected to https://lists.connect.ucsb.edu/ucsb/

I did find the WGS mailing list here:
https://lists.noc.ucsb.edu/mailman/listinfo/ucsb-web

**Comment by loganfranken** [comment]
Yeah, I think the links were supposed to get updated to the "noc" links you mention after the Great E-mail List Migration, but they never did

**Comment by garster** [comment]
![image](https://cloud.githubusercontent.com/assets/4443025/12624542/7cce6776-c4e4-11e5-8c1a-b83a4100024d.png)

**Comment by loganfranken** [comment]
Hey @garster: looks like you fixed this in your own fork?
