### ISSUE TITLE
Email (webstandards@ucsb.edu) on http://webguide.ucsb.edu/about/ does not work.

### ISSUE THREAD

**Issue by garster** [UCSantaBarbara/webguide#96]
On this page http://webguide.ucsb.edu/about/ and maybe others is an email address `webstandards@ucsb.edu` which does not work.

I sent an email to it and received this error:

```
Mail Delivery System [Mailer-Daemon@mx-1.connect.ucsb.edu]
To: Gary Scott 
 Wednesday, January 27, 2016 6:02 AM
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  webstandards@ucsb.edu
    Unrouteable address
```

Does anyone know if this should work. I expect it would not have been placed on the page if it did not work. This address does seem to work webstandards@lists.noc.ucsb.edu but I would rather get the webstandards@ucsb.edu address working if it is supposed to work.

**Comment by loganfranken** [comment]
Hey @garster:

I think webstandards@ucsb.edu was simply moved to webstandards@lists.noc.ucsb.edu and it never got updated.

**Comment by fablio-work** [comment]
All that stuff was setup pre-connect.  I am thinking that NOC may have had an alias for webstandards@ucsb.edu mailto:webstandards@ucsb.edu pointing to the list.
It might not even be possible for NOC to do that now, any alias might have to be done via connect.  Not sure about that though.
It’s worth contacting them about.  I can shoot an email over to them if you want...

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by garster** [comment]
@fablio-work please do look into. I do not know who to contact for Connect related stuff. I think the @ucsb.edu is much cleaner, and if possible I would want to use that.

**Comment by fablio-work** [comment]
Just shot an email off.  Will reply with more info when I have it.

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu

**Comment by fablio-work** [comment]
So the webstandards list is here:  https://lists.noc.ucsb.edu/mailman/listinfo/webstandards https://lists.noc.ucsb.edu/mailman/listinfo/webstandards

It is a mailman list for use by the co-chairs.  Gary is the only subscriber at this time.

So email to that list would need to go to webstandards@lists.noc.ucsb.edu mailto:webstandards@lists.noc.ucsb.edu.

Still trying to clarify the webstandards@ucsb.edu mailto:webstandards@ucsb.edu address (thought that the NOC lists all lived
at @lists.ucsb.edu http://lists.ucsb.edu/ before connect) .  I am guessing that it was either a direct line into the mailman 
list or maybe an alias on the NOC systems pointing to the list webstandards@lists.ucsb.edu mailto:webstandards@lists.ucsb.edu (again, all
prior to connect).

Pretty sure that connect hardware ends up handling any @ucsb.edu http://ucsb.edu/ addresses now.

Aaron Martin  (CNT)
Earth Research Institute
6809 Ellison Hall
UCSB MS-3060
805-893-8415
aaron@eri.ucsb.edu mailto:aaron@eri.ucsb.edu
